#[macro_export]
macro_rules! isolation_aware_user32 {
    (mod_ia_kernel32 = $($p:ident)::+) => {mod __ia_user32_inner {
        #![allow(dead_code)]
        extern crate winapi as __ia_user32_inner_winapi;
        use self::__ia_user32_inner_winapi::*;
        use std::ptr;

        __winapi_basic_isolation_aware!{
            crate_root = $crate;
            ia_kernel32 = ::$($p)::+;
            pub fn IsolationAwareCreateDialogIndirectParamA(
                hInstance: HINSTANCE, lpTemplate: LPCDLGTEMPLATEA, hWndParent: HWND,
                lpDialogFunc: DLGPROC, dwInitParam: LPARAM
            ) -> HWND
                where normal_ident = CreateDialogIndirectParamA,
                      default_ret = ptr::null_mut();
            pub fn IsolationAwareCreateDialogIndirectParamW(
                hInstance: HINSTANCE, lpTemplate: LPCDLGTEMPLATEW, hWndParent: HWND,
                lpDialogFunc: DLGPROC, dwInitParam: LPARAM
            ) -> HWND
                where normal_ident = CreateDialogIndirectParamW,
                      default_ret = ptr::null_mut();
            pub fn IsolationAwareCreateDialogParamA(
                hInstance: HINSTANCE, lpTemplateName: LPCSTR, hWndParent: HWND,
                lpDialogFunc: DLGPROC, dwInitParam: LPARAM
            ) -> HWND
                where normal_ident = CreateDialogParamA,
                      default_ret = ptr::null_mut();
            pub fn IsolationAwareCreateDialogParamW(
                hInstance: HINSTANCE, lpTemplateName: LPCWSTR, hWndParent: HWND,
                lpDialogFunc: DLGPROC, dwInitParam: LPARAM
            ) -> HWND
                where normal_ident = CreateDialogParamW,
                      default_ret = ptr::null_mut();
            pub fn IsolationAwareCreateWindowExA(
                dwExStyle: DWORD, lpClassName: LPCSTR, lpWindowName: LPCSTR, dwStyle: DWORD,
                x: c_int, y: c_int, nWidth: c_int, nHeight: c_int, hWndParent: HWND, hMenu: HMENU,
                hInstance: HINSTANCE, lpParam: LPVOID
            ) -> HWND
                where normal_ident = CreateWindowExA,
                      default_ret = ptr::null_mut();
            pub fn IsolationAwareCreateWindowExW(
                dwExStyle: DWORD, lpClassName: LPCWSTR, lpWindowName: LPCWSTR, dwStyle: DWORD,
                x: c_int, y: c_int, nWidth: c_int, nHeight: c_int, hWndParent: HWND, hMenu: HMENU,
                hInstance: HINSTANCE, lpParam: LPVOID
            ) -> HWND
                where normal_ident = CreateWindowExW,
                      default_ret = ptr::null_mut();
            pub fn IsolationAwareDialogBoxIndirectParamA(
                hInstance: HINSTANCE, hDialogTemplate: LPCDLGTEMPLATEA, hWndParent: HWND,
                lpDialogFunc: DLGPROC, dwInitParam: LPARAM
            ) -> INT_PTR
                where normal_ident = DialogBoxIndirectParamA,
                      default_ret = -1;
            pub fn IsolationAwareDialogBoxIndirectParamW(
                hInstance: HINSTANCE, hDialogTemplate: LPCDLGTEMPLATEW, hWndParent: HWND,
                lpDialogFunc: DLGPROC, dwInitParam: LPARAM
            ) -> INT_PTR
                where normal_ident = DialogBoxIndirectParamW,
                      default_ret = -1;
            // pub fn GetClassInfoA();
            // pub fn GetClassInfoExA();
            pub fn IsolationAwareGetClassInfoExW(
                hinst: HINSTANCE, lpszClass: LPCWSTR, lpwcx: LPWNDCLASSEXW
            ) -> BOOL
                where normal_ident = GetClassInfoExW,
                      default_ret = FALSE;
            pub fn IsolationAwareGetClassInfoW(
                hInstance: HINSTANCE, lpClassName: LPCWSTR, lpWndClass: LPWNDCLASSW
            ) -> BOOL
                where normal_ident = GetClassInfoW,
                      default_ret = FALSE;
            pub fn IsolationAwareMessageBoxA(
                hWnd: HWND, lpText: LPCSTR, lpCaption: LPCSTR, uType: UINT
            ) -> c_int
                where normal_ident = MessageBoxA,
                      default_ret = 0;
            pub fn IsolationAwareMessageBoxExA(
                hWnd: HWND, lpText: LPCSTR, lpCaption: LPCSTR, uType: UINT, wLanguageId: WORD
            ) -> c_int
                where normal_ident = MessageBoxExA,
                      default_ret = 0;
            pub fn IsolationAwareMessageBoxExW(
                hWnd: HWND, lpText: LPCWSTR, lpCaption: LPCWSTR, uType: UINT, wLanguageId: WORD
            ) -> c_int
                where normal_ident = MessageBoxExW,
                      default_ret = 0;
            pub fn IsolationAwareMessageBoxIndirectA(lpmbp: *const MSGBOXPARAMSA) -> c_int
                where normal_ident = MessageBoxIndirectA,
                      default_ret = 0;
            pub fn IsolationAwareMessageBoxIndirectW(lpmbp: *const MSGBOXPARAMSW) -> c_int
                where normal_ident = MessageBoxIndirectW,
                      default_ret = 0;
            pub fn IsolationAwareMessageBoxW(
                hWnd: HWND, lpText: LPCWSTR, lpCaption: LPCWSTR, uType: UINT
            ) -> c_int
                where normal_ident = MessageBoxW,
                      default_ret = 0;
            // pub fn RegisterClassA();
            // pub fn RegisterClassExA();
            pub fn IsolationAwareRegisterClassExW(lpWndClass: *const WNDCLASSEXW) -> ATOM
                where normal_ident = RegisterClassExW,
                      default_ret = 0;
            pub fn IsolationAwareRegisterClassW(lpWndClass: *const WNDCLASSW) -> ATOM
                where normal_ident = RegisterClassW,
                      default_ret = 0;
            pub fn IsolationAwareUnregisterClassA(lpClassName: LPCSTR, hInstance: HINSTANCE) -> BOOL
                where normal_ident = UnregisterClassA,
                      default_ret = FALSE;
            pub fn IsolationAwareUnregisterClassW(
                lpClassName: LPCWSTR, hInstance: HINSTANCE
            ) -> BOOL
                where normal_ident = UnregisterClassW,
                      default_ret = FALSE;
        }

        pub use self::{
            IsolationAwareCreateDialogIndirectParamA as CreateDialogIndirectParamA,
            IsolationAwareCreateDialogIndirectParamW as CreateDialogIndirectParamW,
            IsolationAwareCreateDialogParamA as CreateDialogParamA,
            IsolationAwareCreateDialogParamW as CreateDialogParamW,
            IsolationAwareCreateWindowExA as CreateWindowExA,
            IsolationAwareCreateWindowExW as CreateWindowExW,
            IsolationAwareDialogBoxIndirectParamA as DialogBoxIndirectParamA,
            IsolationAwareDialogBoxIndirectParamW as DialogBoxIndirectParamW,
            IsolationAwareGetClassInfoExW as GetClassInfoExW,
            IsolationAwareGetClassInfoW as GetClassInfoW,
            IsolationAwareMessageBoxA as MessageBoxA,
            IsolationAwareMessageBoxExA as MessageBoxExA,
            IsolationAwareMessageBoxExW as MessageBoxExW,
            IsolationAwareMessageBoxIndirectA as MessageBoxIndirectA,
            IsolationAwareMessageBoxIndirectW as MessageBoxIndirectW,
            IsolationAwareMessageBoxW as MessageBoxW,
            IsolationAwareRegisterClassExW as RegisterClassExW,
            IsolationAwareRegisterClassW as RegisterClassW,
            IsolationAwareUnregisterClassA as UnregisterClassA,
            IsolationAwareUnregisterClassW as UnregisterClassW
        };

        pub use $crate::{
            ActivateKeyboardLayout,
            AddClipboardFormatListener,
            AdjustWindowRect,
            AdjustWindowRectEx,
            AllowSetForegroundWindow,
            AnimateWindow,
            AnyPopup,
            AppendMenuA,
            AppendMenuW,
            ArrangeIconicWindows,
            AttachThreadInput,
            // BeginDeferWindowPos,
            BeginPaint,
            BlockInput,
            BringWindowToTop,
            // BroadcastSystemMessage,
            BroadcastSystemMessageA,
            // BroadcastSystemMessageExA,
            // BroadcastSystemMessageExW,
            BroadcastSystemMessageW,
            CalculatePopupWindowPosition,
            CallMsgFilterA,
            CallMsgFilterW,
            CallNextHookEx,
            CallWindowProcA,
            CallWindowProcW,
            CancelShutdown,
            // CascadeChildWindows,
            CascadeWindows,
            ChangeClipboardChain,
            ChangeDisplaySettingsA,
            ChangeDisplaySettingsExA,
            ChangeDisplaySettingsExW,
            ChangeDisplaySettingsW,
            ChangeMenuA,
            ChangeMenuW,
            ChangeWindowMessageFilter,
            ChangeWindowMessageFilterEx,
            CharLowerA,
            CharLowerBuffA,
            CharLowerBuffW,
            CharLowerW,
            CharNextA,
            CharNextExA,
            CharNextW,
            CharPrevA,
            CharPrevExA,
            CharPrevW,
            // CharToOemA,
            // CharToOemBuffA,
            // CharToOemBuffW,
            // CharToOemW,
            CharUpperA,
            CharUpperBuffA,
            CharUpperBuffW,
            CharUpperW,
            CheckDlgButton,
            CheckMenuItem,
            CheckMenuRadioItem,
            CheckRadioButton,
            ChildWindowFromPoint,
            ChildWindowFromPointEx,
            ClientToScreen,
            ClipCursor,
            CloseClipboard,
            CloseDesktop,
            // CloseGestureInfoHandle,
            CloseTouchInputHandle,
            CloseWindow,
            CloseWindowStation,
            CopyAcceleratorTableA,
            CopyAcceleratorTableW,
            CopyIcon,
            CopyImage,
            CopyRect,
            CountClipboardFormats,
            CreateAcceleratorTableA,
            CreateAcceleratorTableW,
            CreateCaret,
            CreateCursor,
            CreateDesktopA,
            // CreateDesktopExA,
            // CreateDesktopExW,
            CreateDesktopW,
            CreateIcon,
            CreateIconFromResource,
            CreateIconFromResourceEx,
            CreateIconIndirect,
            CreateMDIWindowA,
            CreateMDIWindowW,
            CreateMenu,
            CreatePopupMenu,
            CreateWindowStationA,
            CreateWindowStationW,
            // DdeAbandonTransaction,
            // DdeAccessData,
            // DdeAddData,
            // DdeClientTransaction,
            // DdeCmpStringHandles,
            // DdeConnect,
            // DdeConnectList,
            // DdeCreateDataHandle,
            // DdeCreateStringHandleA,
            // DdeCreateStringHandleW,
            // DdeDisconnect,
            // DdeDisconnectList,
            // DdeEnableCallback,
            // DdeFreeDataHandle,
            // DdeFreeStringHandle,
            // DdeGetData,
            // DdeGetLastError,
            // DdeImpersonateClient,
            // DdeInitializeA,
            // DdeInitializeW,
            // DdeKeepStringHandle,
            // DdeNameService,
            // DdePostAdvise,
            // DdeQueryConvInfo,
            // DdeQueryNextServer,
            // DdeQueryStringA,
            // DdeQueryStringW,
            // DdeReconnect,
            // DdeSetQualityOfService,
            // DdeSetUserHandle,
            // DdeUnaccessData,
            // DdeUninitialize,
            DefDlgProcA,
            DefDlgProcW,
            DefFrameProcA,
            DefFrameProcW,
            DefMDIChildProcA,
            DefMDIChildProcW,
            DefRawInputProc,
            DefWindowProcA,
            DefWindowProcW,
            DeferWindowPos,
            DeleteMenu,
            DeregisterShellHookWindow,
            DestroyAcceleratorTable,
            DestroyCaret,
            DestroyCursor,
            DestroyIcon,
            DestroyMenu,
            DestroyWindow,
            DialogBoxParamA,
            DialogBoxParamW,
            // DisableProcessWindowsGhosting,
            DispatchMessageA,
            DispatchMessageW,
            // DisplayConfigGetDeviceInfo,
            // DisplayConfigSetDeviceInfo,
            DlgDirListA,
            DlgDirListComboBoxA,
            DlgDirListComboBoxW,
            DlgDirListW,
            DlgDirSelectComboBoxExA,
            DlgDirSelectComboBoxExW,
            DlgDirSelectExA,
            DlgDirSelectExW,
            DragDetect,
            DragObject,
            DrawAnimatedRects,
            DrawCaption,
            DrawEdge,
            DrawFocusRect,
            // DrawFrame,
            DrawFrameControl,
            DrawIcon,
            DrawIconEx,
            DrawMenuBar,
            DrawStateA,
            DrawStateW,
            DrawTextA,
            DrawTextExA,
            DrawTextExW,
            DrawTextW,
            // EditWndProc,
            EmptyClipboard,
            EnableMenuItem,
            EnableMouseInPointer,
            EnableScrollBar,
            // EnableSessionForMMCSS,
            EnableWindow,
            EndDeferWindowPos,
            EndDialog,
            EndMenu,
            EndPaint,
            EndTask,
            EnumChildWindows,
            EnumClipboardFormats,
            EnumDesktopWindows,
            EnumDesktopsA,
            EnumDesktopsW,
            EnumDisplayDevicesA,
            EnumDisplayDevicesW,
            EnumDisplayMonitors,
            EnumDisplaySettingsA,
            EnumDisplaySettingsExA,
            EnumDisplaySettingsExW,
            EnumDisplaySettingsW,
            EnumPropsA,
            EnumPropsExA,
            EnumPropsExW,
            EnumPropsW,
            EnumThreadWindows,
            EnumWindowStationsA,
            EnumWindowStationsW,
            EnumWindows,
            // EqualRect,
            // EvaluateProximityToPolygon,
            // EvaluateProximityToRect,
            ExcludeUpdateRgn,
            ExitWindowsEx,
            FillRect,
            FindWindowA,
            FindWindowExA,
            FindWindowExW,
            FindWindowW,
            FlashWindow,
            FlashWindowEx,
            FrameRect,
            // FreeDDElParam,
            GetActiveWindow,
            // GetAltTabInfo,
            // GetAltTabInfoA,
            // GetAltTabInfoW,
            GetAncestor,
            GetAsyncKeyState,
            // GetAutoRotationState,
            // GetCIMSSM,
            GetCapture,
            GetCaretBlinkTime,
            GetCaretPos,
            // GetClassInfoA,
            // GetClassInfoExA,
            GetClassLongA,
            GetClassLongPtrA,
            GetClassLongPtrW,
            GetClassLongW,
            GetClassNameA,
            GetClassNameW,
            GetClassWord,
            GetClientRect,
            GetClipCursor,
            GetClipboardData,
            GetClipboardFormatNameA,
            GetClipboardFormatNameW,
            GetClipboardOwner,
            GetClipboardSequenceNumber,
            GetClipboardViewer,
            // GetComboBoxInfo,
            // GetCurrentInputMessageSource,
            GetCursor,
            // GetCursorInfo,
            GetCursorPos,
            GetDC,
            GetDCEx,
            GetDesktopWindow,
            GetDialogBaseUnits,
            // GetDisplayAutoRotationPreferences,
            // GetDisplayConfigBufferSizes,
            GetDlgCtrlID,
            GetDlgItem,
            GetDlgItemInt,
            GetDlgItemTextA,
            GetDlgItemTextW,
            GetDoubleClickTime,
            GetFocus,
            GetForegroundWindow,
            // GetGUIThreadInfo,
            // GetGestureConfig,
            // GetGestureExtraArgs,
            // GetGestureInfo,
            // GetGuiResources,
            GetIconInfo,
            // GetIconInfoExA,
            // GetIconInfoExW,
            // GetInputDesktop,
            // GetInputLocaleInfo,
            // GetInputState,
            GetKBCodePage,
            GetKeyNameTextA,
            GetKeyNameTextW,
            GetKeyState,
            GetKeyboardLayout,
            GetKeyboardLayoutList,
            GetKeyboardLayoutNameA,
            GetKeyboardLayoutNameW,
            GetKeyboardState,
            GetKeyboardType,
            GetLastActivePopup,
            // GetLastInputInfo,
            // GetLayeredWindowAttributes,
            // GetListBoxInfo,
            GetMenu,
            // GetMenuBarInfo,
            // GetMenuCheckMarkDimensions,
            // GetMenuContextHelpId,
            // GetMenuDefaultItem,
            // GetMenuInfo,
            // GetMenuItemCount,
            // GetMenuItemID,
            // GetMenuItemInfoA,
            // GetMenuItemInfoW,
            // GetMenuItemRect,
            // GetMenuState,
            // GetMenuStringA,
            // GetMenuStringW,
            // GetMessageA,
            // GetMessageExtraInfo,
            // GetMessagePos,
            GetMessageTime,
            GetMessageW,
            GetMonitorInfoA,
            GetMonitorInfoW,
            // GetMouseMovePointsEx,
            GetNextDlgGroupItem,
            GetNextDlgTabItem,
            GetOpenClipboardWindow,
            GetParent,
            GetPhysicalCursorPos,
            // GetPointerCursorId,
            // GetPointerDevice,
            // GetPointerDeviceCursors,
            // GetPointerDeviceProperties,
            // GetPointerDeviceRects,
            // GetPointerDevices,
            // GetPointerFrameInfo,
            // GetPointerFrameInfoHistory,
            // GetPointerFramePenInfo,
            // GetPointerFramePenInfoHistory,
            // GetPointerFrameTouchInfo,
            // GetPointerFrameTouchInfoHistory,
            // GetPointerInfo,
            // GetPointerInfoHistory,
            // GetPointerInputTransform,
            // GetPointerPenInfo,
            // GetPointerPenInfoHistory,
            // GetPointerTouchInfo,
            // GetPointerTouchInfoHistory,
            GetPointerType,
            // GetPriorityClipboardFormat,
            // GetProcessDefaultLayout,
            // GetProcessWindowStation,
            GetPropA,
            GetPropW,
            GetQueueStatus,
            GetRawInputBuffer,
            GetRawInputData,
            GetRawInputDeviceInfoA,
            GetRawInputDeviceInfoW,
            GetRawInputDeviceList,
            // GetRawPointerDeviceData,
            GetRegisteredRawInputDevices,
            // GetScrollBarInfo,
            GetScrollInfo,
            GetScrollPos,
            GetScrollRange,
            GetShellWindow,
            GetSubMenu,
            GetSysColor,
            GetSysColorBrush,
            GetSystemMenu,
            GetSystemMetrics,
            GetTabbedTextExtentA,
            GetTabbedTextExtentW,
            GetThreadDesktop,
            // GetTitleBarInfo,
            GetTopWindow,
            GetTouchInputInfo,
            // GetUnpredictedMessagePos,
            GetUpdateRect,
            GetUpdateRgn,
            GetUpdatedClipboardFormats,
            // GetUserObjectInformationA,
            // GetUserObjectInformationW,
            // GetUserObjectSecurity,
            GetWindow,
            GetWindowContextHelpId,
            GetWindowDC,
            // GetWindowDisplayAffinity,
            // GetWindowFeedbackSetting,
            // GetWindowInfo,
            GetWindowLongA,
            GetWindowLongPtrA,
            GetWindowLongPtrW,
            GetWindowLongW,
            // GetWindowModuleFileName,
            GetWindowModuleFileNameA,
            GetWindowModuleFileNameW,
            GetWindowPlacement,
            GetWindowRect,
            GetWindowRgn,
            GetWindowRgnBox,
            GetWindowTextA,
            GetWindowTextLengthA,
            GetWindowTextLengthW,
            GetWindowTextW,
            GetWindowThreadProcessId,
            GetWindowWord,
            GrayStringA,
            GrayStringW,
            HideCaret,
            HiliteMenuItem,
            // IMPGetIMEA,
            // IMPGetIMEW,
            // IMPQueryIMEA,
            // IMPQueryIMEW,
            // IMPSetIMEA,
            // IMPSetIMEW,
            // ImpersonateDdeClientWindow,
            // InSendMessage,
            // InSendMessageEx,
            InflateRect,
            // InitializeTouchInjection,
            // InjectTouchInput,
            InsertMenuA,
            InsertMenuItemA,
            InsertMenuItemW,
            InsertMenuW,
            InternalGetWindowText,
            IntersectRect,
            InvalidateRect,
            InvalidateRgn,
            InvertRect,
            IsCharAlphaA,
            IsCharAlphaNumericA,
            IsCharAlphaNumericW,
            IsCharAlphaW,
            IsCharLowerA,
            IsCharLowerW,
            IsCharUpperA,
            IsCharUpperW,
            IsChild,
            IsClipboardFormatAvailable,
            IsDialogMessageA,
            IsDialogMessageW,
            IsDlgButtonChecked,
            IsGUIThread,
            IsHungAppWindow,
            IsIconic,
            IsImmersiveProcess,
            // IsInDesktopWindowBand,
            IsMenu,
            IsMouseInPointerEnabled,
            IsProcessDPIAware,
            IsRectEmpty,
            IsTouchWindow,
            IsWinEventHookInstalled,
            IsWindow,
            IsWindowEnabled,
            IsWindowUnicode,
            IsWindowVisible,
            IsWow64Message,
            IsZoomed,
            KillTimer,
            LoadAcceleratorsA,
            LoadAcceleratorsW,
            LoadBitmapA,
            LoadBitmapW,
            LoadCursorA,
            LoadCursorFromFileA,
            LoadCursorFromFileW,
            LoadCursorW,
            LoadIconA,
            LoadIconW,
            LoadImageA,
            LoadImageW,
            LoadKeyboardLayoutA,
            LoadKeyboardLayoutW,
            LoadMenuA,
            LoadMenuIndirectA,
            LoadMenuIndirectW,
            LoadMenuW,
            LoadStringA,
            LoadStringW,
            LockSetForegroundWindow,
            LockWindowUpdate,
            LockWorkStation,
            // LogicalToPhysicalPoint,
            // LogicalToPhysicalPointForPerMonitorDPI,
            LookupIconIdFromDirectory,
            LookupIconIdFromDirectoryEx,
            MapDialogRect,
            MapVirtualKeyA,
            MapVirtualKeyExA,
            MapVirtualKeyExW,
            MapVirtualKeyW,
            MapWindowPoints,
            MenuItemFromPoint,
            MessageBeep,
            // MessageBoxTimeoutA,
            // MessageBoxTimeoutW,
            ModifyMenuA,
            ModifyMenuW,
            MonitorFromPoint,
            MonitorFromRect,
            MonitorFromWindow,
            MoveWindow,
            MsgWaitForMultipleObjects,
            MsgWaitForMultipleObjectsEx,
            NotifyWinEvent,
            OemKeyScan,
            OemToCharA,
            OemToCharBuffA,
            OemToCharBuffW,
            OemToCharW,
            OffsetRect,
            OpenClipboard,
            OpenDesktopA,
            OpenDesktopW,
            OpenIcon,
            OpenInputDesktop,
            OpenWindowStationA,
            OpenWindowStationW,
            PackDDElParam,
            // PackTouchHitTestingProximityEvaluation,
            PaintDesktop,
            PeekMessageA,
            PeekMessageW,
            // PhysicalToLogicalPoint,
            // PhysicalToLogicalPointForPerMonitorDPI,
            PostMessageA,
            PostMessageW,
            PostQuitMessage,
            PostThreadMessageA,
            PostThreadMessageW,
            PrintWindow,
            // PrivateExtractIconsA,
            // PrivateExtractIconsW,
            PtInRect,
            // QueryDisplayConfig,
            RealChildWindowFromPoint,
            RealGetWindowClass,
            RealGetWindowClassA,
            RealGetWindowClassW,
            RedrawWindow,
            // RegisterClassA,
            // RegisterClassExA,
            RegisterClipboardFormatA,
            RegisterClipboardFormatW,
            RegisterDeviceNotificationA,
            RegisterDeviceNotificationW,
            RegisterHotKey,
            // RegisterPointerDeviceNotifications,
            // RegisterPointerInputTarget,
            // RegisterPowerSettingNotification,
            RegisterRawInputDevices,
            // RegisterShellHookWindow,
            // RegisterSuspendResumeNotification,
            // RegisterTouchHitTestingWindow,
            RegisterTouchWindow,
            RegisterWindowMessageA,
            RegisterWindowMessageW,
            ReleaseCapture,
            ReleaseDC,
            // RemoveClipboardFormatListener,
            // RemoveMenu,
            RemovePropA,
            RemovePropW,
            // ReplyMessage,
            // ReuseDDElParam,
            ScreenToClient,
            ScrollDC,
            ScrollWindow,
            ScrollWindowEx,
            SendDlgItemMessageA,
            SendDlgItemMessageW,
            // SendIMEMessageExA,
            // SendIMEMessageExW,
            SendInput,
            SendMessageA,
            // SendMessageCallbackA,
            // SendMessageCallbackW,
            SendMessageTimeoutA,
            SendMessageTimeoutW,
            SendMessageW,
            SendNotifyMessageA,
            SendNotifyMessageW,
            SetActiveWindow,
            SetCapture,
            SetCaretBlinkTime,
            SetCaretPos,
            SetClassLongA,
            SetClassLongPtrA,
            SetClassLongPtrW,
            SetClassLongW,
            SetClassWord,
            SetClipboardData,
            SetClipboardViewer,
            // SetCoalescableTimer,
            SetCursor,
            SetCursorPos,
            // SetDebugErrorLevel,
            // SetDeskWallpaper,
            // SetDisplayAutoRotationPreferences,
            // SetDisplayConfig,
            SetDlgItemInt,
            SetDlgItemTextA,
            SetDlgItemTextW,
            SetDoubleClickTime,
            SetFocus,
            SetForegroundWindow,
            // SetGestureConfig,
            SetKeyboardState,
            SetLastErrorEx,
            SetLayeredWindowAttributes,
            SetMenu,
            // SetMenuContextHelpId,
            // SetMenuDefaultItem,
            // SetMenuInfo,
            // SetMenuItemBitmaps,
            // SetMenuItemInfoA,
            // SetMenuItemInfoW,
            // SetMessageExtraInfo,
            // SetMessageQueue,
            SetParent,
            SetPhysicalCursorPos,
            // SetProcessDPIAware,
            // SetProcessDefaultLayout,
            // SetProcessRestrictionExemption,
            // SetProcessWindowStation,
            SetPropA,
            SetPropW,
            SetRect,
            SetRectEmpty,
            SetScrollInfo,
            SetScrollPos,
            SetScrollRange,
            // SetShellWindow,
            SetSysColors,
            SetSystemCursor,
            SetThreadDesktop,
            SetTimer,
            // SetUserObjectInformationA,
            // SetUserObjectInformationW,
            // SetUserObjectSecurity,
            SetWinEventHook,
            SetWindowContextHelpId,
            // SetWindowDisplayAffinity,
            // SetWindowFeedbackSetting,
            SetWindowLongA,
            SetWindowLongPtrA,
            SetWindowLongPtrW,
            SetWindowLongW,
            SetWindowPlacement,
            SetWindowPos,
            SetWindowRgn,
            SetWindowTextA,
            SetWindowTextW,
            SetWindowWord,
            // SetWindowsHookA,
            SetWindowsHookExA,
            SetWindowsHookExW,
            // SetWindowsHookW,
            ShowCaret,
            ShowCursor,
            ShowOwnedPopups,
            ShowScrollBar,
            // ShowSystemCursor,
            ShowWindow,
            ShowWindowAsync,
            // ShutdownBlockReasonCreate,
            // ShutdownBlockReasonDestroy,
            // ShutdownBlockReasonQuery,
            // SkipPointerFrameMessages,
            // SoundSentry,
            // SubtractRect,
            SwapMouseButton,
            SwitchDesktop,
            // SwitchToThisWindow,
            SystemParametersInfoA,
            SystemParametersInfoW,
            TabbedTextOutA,
            TabbedTextOutW,
            // TileChildWindows,
            // TileWindows,
            // ToAscii,
            // ToAsciiEx,
            ToUnicode,
            // ToUnicodeEx,
            TrackMouseEvent,
            TrackPopupMenu,
            TrackPopupMenuEx,
            // TranslateAccelerator,
            // TranslateAcceleratorA,
            // TranslateAcceleratorW,
            // TranslateMDISysAccel,
            TranslateMessage,
            UnhookWinEvent,
            // UnhookWindowsHook,
            UnhookWindowsHookEx,
            UnionRect,
            UnloadKeyboardLayout,
            UnpackDDElParam,
            UnregisterDeviceNotification,
            UnregisterHotKey,
            // UnregisterPointerInputTarget,
            // UnregisterPowerSettingNotification,
            // UnregisterSuspendResumeNotification,
            // UnregisterTouchWindow,
            UpdateLayeredWindow,
            // UpdateLayeredWindowIndirect,
            UpdateWindow,
            UserHandleGrantAccess,
            ValidateRect,
            ValidateRgn,
            VkKeyScanA,
            VkKeyScanExA,
            VkKeyScanExW,
            VkKeyScanW,
            // WINNLSEnableIME,
            // WINNLSGetEnableStatus,
            // WINNLSGetIMEHotkey,
            WaitForInputIdle,
            WaitMessage,
            WinHelpA,
            WinHelpW,
            WindowFromDC,
            // WindowFromPhysicalPoint,
            WindowFromPoint,
            keybd_event,
            mouse_event,
            // wsprintfA,
            // wsprintfW,
            // wvsprintfA,
            // wvsprintfW,
        };
    }
    pub use self::__ia_user32_inner::*;
    }
}

#[cfg(test)]
pub mod ia_kernel32 {
    isolation_aware_kernel32!();
}

#[cfg(test)]
isolation_aware_user32!(mod_ia_kernel32 = isolation_aware::ia_kernel32);
