// Copyright © 2016-2017 winapi-rs developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// All files in the project carrying such notice may not be copied, modified, or distributed
// except according to those terms.
#![cfg(windows)]
extern crate winapi;
use std::mem::{size_of, align_of};
#[cfg(all(target_arch = "x86", feature = "d3d9caps"))] #[test]
fn shared_d3d9caps() {
    use winapi::shared::d3d9caps::*;
    assert_eq!(size_of::<D3DVSHADERCAPS2_0>(), 16);
    assert_eq!(align_of::<D3DVSHADERCAPS2_0>(), 4);
    assert_eq!(size_of::<D3DPSHADERCAPS2_0>(), 20);
    assert_eq!(align_of::<D3DPSHADERCAPS2_0>(), 4);
    assert_eq!(size_of::<D3DOVERLAYCAPS>(), 12);
    assert_eq!(align_of::<D3DOVERLAYCAPS>(), 4);
    assert_eq!(size_of::<D3DCONTENTPROTECTIONCAPS>(), 36);
    // FIXME packed(4)
    // assert_eq!(align_of::<D3DCONTENTPROTECTIONCAPS>(), 4);
    assert_eq!(size_of::<D3DCAPS9>(), 304);
    assert_eq!(align_of::<D3DCAPS9>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "d3d9caps"))] #[test]
fn shared_d3d9caps() {
    use winapi::shared::d3d9caps::*;
    assert_eq!(size_of::<D3DVSHADERCAPS2_0>(), 16);
    assert_eq!(align_of::<D3DVSHADERCAPS2_0>(), 4);
    assert_eq!(size_of::<D3DPSHADERCAPS2_0>(), 20);
    assert_eq!(align_of::<D3DPSHADERCAPS2_0>(), 4);
    assert_eq!(size_of::<D3DOVERLAYCAPS>(), 12);
    assert_eq!(align_of::<D3DOVERLAYCAPS>(), 4);
    assert_eq!(size_of::<D3DCONTENTPROTECTIONCAPS>(), 40);
    assert_eq!(align_of::<D3DCONTENTPROTECTIONCAPS>(), 8);
    assert_eq!(size_of::<D3DCAPS9>(), 304);
    assert_eq!(align_of::<D3DCAPS9>(), 4);
}
#[cfg(all(target_arch = "x86", feature = "d3d9types"))] #[test]
fn shared_d3d9types() {
    use winapi::shared::d3d9types::*;
    assert_eq!(size_of::<D3DVECTOR>(), 12);
    assert_eq!(align_of::<D3DVECTOR>(), 4);
    assert_eq!(size_of::<D3DCOLORVALUE>(), 16);
    assert_eq!(align_of::<D3DCOLORVALUE>(), 4);
    assert_eq!(size_of::<D3DRECT>(), 16);
    assert_eq!(align_of::<D3DRECT>(), 4);
    assert_eq!(size_of::<D3DMATRIX>(), 64);
    assert_eq!(align_of::<D3DMATRIX>(), 4);
    assert_eq!(size_of::<D3DVIEWPORT9>(), 24);
    assert_eq!(align_of::<D3DVIEWPORT9>(), 4);
    assert_eq!(size_of::<D3DCLIPSTATUS9>(), 8);
    assert_eq!(align_of::<D3DCLIPSTATUS9>(), 4);
    assert_eq!(size_of::<D3DMATERIAL9>(), 68);
    assert_eq!(align_of::<D3DMATERIAL9>(), 4);
    assert_eq!(size_of::<D3DLIGHT9>(), 104);
    assert_eq!(align_of::<D3DLIGHT9>(), 4);
    assert_eq!(size_of::<D3DVERTEXELEMENT9>(), 8);
    assert_eq!(align_of::<D3DVERTEXELEMENT9>(), 2);
    assert_eq!(size_of::<D3DDISPLAYMODE>(), 16);
    assert_eq!(align_of::<D3DDISPLAYMODE>(), 4);
    assert_eq!(size_of::<D3DDEVICE_CREATION_PARAMETERS>(), 16);
    assert_eq!(align_of::<D3DDEVICE_CREATION_PARAMETERS>(), 4);
    assert_eq!(size_of::<D3DPRESENT_PARAMETERS>(), 56);
    assert_eq!(align_of::<D3DPRESENT_PARAMETERS>(), 4);
    assert_eq!(size_of::<D3DGAMMARAMP>(), 1536);
    assert_eq!(align_of::<D3DGAMMARAMP>(), 2);
    assert_eq!(size_of::<D3DVERTEXBUFFER_DESC>(), 24);
    assert_eq!(align_of::<D3DVERTEXBUFFER_DESC>(), 4);
    assert_eq!(size_of::<D3DINDEXBUFFER_DESC>(), 20);
    assert_eq!(align_of::<D3DINDEXBUFFER_DESC>(), 4);
    assert_eq!(size_of::<D3DSURFACE_DESC>(), 32);
    assert_eq!(align_of::<D3DSURFACE_DESC>(), 4);
    assert_eq!(size_of::<D3DVOLUME_DESC>(), 28);
    assert_eq!(align_of::<D3DVOLUME_DESC>(), 4);
    assert_eq!(size_of::<D3DLOCKED_RECT>(), 8);
    assert_eq!(align_of::<D3DLOCKED_RECT>(), 4);
    assert_eq!(size_of::<D3DBOX>(), 24);
    assert_eq!(align_of::<D3DBOX>(), 4);
    assert_eq!(size_of::<D3DLOCKED_BOX>(), 12);
    assert_eq!(align_of::<D3DLOCKED_BOX>(), 4);
    assert_eq!(size_of::<D3DRANGE>(), 8);
    assert_eq!(align_of::<D3DRANGE>(), 4);
    assert_eq!(size_of::<D3DRECTPATCH_INFO>(), 28);
    assert_eq!(align_of::<D3DRECTPATCH_INFO>(), 4);
    assert_eq!(size_of::<D3DTRIPATCH_INFO>(), 16);
    assert_eq!(align_of::<D3DTRIPATCH_INFO>(), 4);
    assert_eq!(size_of::<D3DADAPTER_IDENTIFIER9>(), 1100);
    // FIXME packed(4)
    // assert_eq!(align_of::<D3DADAPTER_IDENTIFIER9>(), 4);
    assert_eq!(size_of::<D3DRASTER_STATUS>(), 8);
    assert_eq!(align_of::<D3DRASTER_STATUS>(), 4);
    assert_eq!(size_of::<D3DRESOURCESTATS>(), 44);
    assert_eq!(align_of::<D3DRESOURCESTATS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_RESOURCEMANAGER>(), 352);
    assert_eq!(align_of::<D3DDEVINFO_RESOURCEMANAGER>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3DVERTEXSTATS>(), 8);
    assert_eq!(align_of::<D3DDEVINFO_D3DVERTEXSTATS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_VCACHE>(), 16);
    assert_eq!(align_of::<D3DDEVINFO_VCACHE>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9PIPELINETIMINGS>(), 16);
    assert_eq!(align_of::<D3DDEVINFO_D3D9PIPELINETIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9INTERFACETIMINGS>(), 20);
    assert_eq!(align_of::<D3DDEVINFO_D3D9INTERFACETIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9STAGETIMINGS>(), 8);
    assert_eq!(align_of::<D3DDEVINFO_D3D9STAGETIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9BANDWIDTHTIMINGS>(), 20);
    assert_eq!(align_of::<D3DDEVINFO_D3D9BANDWIDTHTIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9CACHEUTILIZATION>(), 8);
    assert_eq!(align_of::<D3DDEVINFO_D3D9CACHEUTILIZATION>(), 4);
    assert_eq!(size_of::<D3DMEMORYPRESSURE>(), 20);
    // FIXME packed(4)
    // assert_eq!(align_of::<D3DMEMORYPRESSURE>(), 4);
    assert_eq!(size_of::<D3DCOMPOSERECTDESC>(), 8);
    assert_eq!(align_of::<D3DCOMPOSERECTDESC>(), 2);
    assert_eq!(size_of::<D3DCOMPOSERECTDESTINATION>(), 8);
    assert_eq!(align_of::<D3DCOMPOSERECTDESTINATION>(), 2);
    assert_eq!(size_of::<D3DPRESENTSTATS>(), 28);
    // FIXME packed(4)
    // assert_eq!(align_of::<D3DPRESENTSTATS>(), 4);
    assert_eq!(size_of::<D3DDISPLAYMODEEX>(), 24);
    assert_eq!(align_of::<D3DDISPLAYMODEEX>(), 4);
    assert_eq!(size_of::<D3DDISPLAYMODEFILTER>(), 12);
    assert_eq!(align_of::<D3DDISPLAYMODEFILTER>(), 4);
    assert_eq!(size_of::<D3D_OMAC>(), 16);
    assert_eq!(align_of::<D3D_OMAC>(), 1);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERY_INPUT>(), 24);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERY_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT>(), 44);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS>(), 4);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYPROTECTION_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYPROTECTION_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYCHANNELTYPE_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYCHANNELTYPE_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYDEVICEHANDLE_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYDEVICEHANDLE_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_INPUT>(), 28);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESSCOUNT_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESSCOUNT_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_INPUT>(), 28);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNRESTRICTEDPROTECTEDSHAREDRESOURCECOUNT_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNRESTRICTEDPROTECTEDSHAREDRESOURCECOUNT_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_INPUT>(), 32);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_INPUT>(), 36);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT>(), 64);
    // FIXME packed(4)
    // assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYINFOBUSTYPE_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYINFOBUSTYPE_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUIDCOUNT_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUIDCOUNT_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_INPUT>(), 28);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_OUTPUT>(), 64);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNCOMPRESSEDENCRYPTIONLEVEL_OUTPUT>(), 60);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNCOMPRESSEDENCRYPTIONLEVEL_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT>(), 40);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_OUTPUT>(), 44);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_OUTPUT>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREINITIALIZE>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREINITIALIZE>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREPROTECTION>(), 44);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREPROTECTION>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURECRYPTOSESSION>(), 52);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURECRYPTOSESSION>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURESHAREDRESOURCE>(), 52);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURESHAREDRESOURCE>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREUNCOMPRESSEDENCRYPTION>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREUNCOMPRESSEDENCRYPTION>(), 4);
    assert_eq!(size_of::<D3DENCRYPTED_BLOCK_INFO>(), 12);
    assert_eq!(align_of::<D3DENCRYPTED_BLOCK_INFO>(), 4);
    assert_eq!(size_of::<D3DAES_CTR_IV>(), 16);
    // FIXME packed(4)
    // assert_eq!(align_of::<D3DAES_CTR_IV>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "d3d9types"))] #[test]
fn shared_d3d9types() {
    use winapi::shared::d3d9types::*;
    assert_eq!(size_of::<D3DVECTOR>(), 12);
    assert_eq!(align_of::<D3DVECTOR>(), 4);
    assert_eq!(size_of::<D3DCOLORVALUE>(), 16);
    assert_eq!(align_of::<D3DCOLORVALUE>(), 4);
    assert_eq!(size_of::<D3DRECT>(), 16);
    assert_eq!(align_of::<D3DRECT>(), 4);
    assert_eq!(size_of::<D3DMATRIX>(), 64);
    assert_eq!(align_of::<D3DMATRIX>(), 4);
    assert_eq!(size_of::<D3DVIEWPORT9>(), 24);
    assert_eq!(align_of::<D3DVIEWPORT9>(), 4);
    assert_eq!(size_of::<D3DCLIPSTATUS9>(), 8);
    assert_eq!(align_of::<D3DCLIPSTATUS9>(), 4);
    assert_eq!(size_of::<D3DMATERIAL9>(), 68);
    assert_eq!(align_of::<D3DMATERIAL9>(), 4);
    assert_eq!(size_of::<D3DLIGHT9>(), 104);
    assert_eq!(align_of::<D3DLIGHT9>(), 4);
    assert_eq!(size_of::<D3DVERTEXELEMENT9>(), 8);
    assert_eq!(align_of::<D3DVERTEXELEMENT9>(), 2);
    assert_eq!(size_of::<D3DDISPLAYMODE>(), 16);
    assert_eq!(align_of::<D3DDISPLAYMODE>(), 4);
    assert_eq!(size_of::<D3DDEVICE_CREATION_PARAMETERS>(), 24);
    assert_eq!(align_of::<D3DDEVICE_CREATION_PARAMETERS>(), 8);
    assert_eq!(size_of::<D3DPRESENT_PARAMETERS>(), 64);
    assert_eq!(align_of::<D3DPRESENT_PARAMETERS>(), 8);
    assert_eq!(size_of::<D3DGAMMARAMP>(), 1536);
    assert_eq!(align_of::<D3DGAMMARAMP>(), 2);
    assert_eq!(size_of::<D3DVERTEXBUFFER_DESC>(), 24);
    assert_eq!(align_of::<D3DVERTEXBUFFER_DESC>(), 4);
    assert_eq!(size_of::<D3DINDEXBUFFER_DESC>(), 20);
    assert_eq!(align_of::<D3DINDEXBUFFER_DESC>(), 4);
    assert_eq!(size_of::<D3DSURFACE_DESC>(), 32);
    assert_eq!(align_of::<D3DSURFACE_DESC>(), 4);
    assert_eq!(size_of::<D3DVOLUME_DESC>(), 28);
    assert_eq!(align_of::<D3DVOLUME_DESC>(), 4);
    assert_eq!(size_of::<D3DLOCKED_RECT>(), 16);
    assert_eq!(align_of::<D3DLOCKED_RECT>(), 8);
    assert_eq!(size_of::<D3DBOX>(), 24);
    assert_eq!(align_of::<D3DBOX>(), 4);
    assert_eq!(size_of::<D3DLOCKED_BOX>(), 16);
    assert_eq!(align_of::<D3DLOCKED_BOX>(), 8);
    assert_eq!(size_of::<D3DRANGE>(), 8);
    assert_eq!(align_of::<D3DRANGE>(), 4);
    assert_eq!(size_of::<D3DRECTPATCH_INFO>(), 28);
    assert_eq!(align_of::<D3DRECTPATCH_INFO>(), 4);
    assert_eq!(size_of::<D3DTRIPATCH_INFO>(), 16);
    assert_eq!(align_of::<D3DTRIPATCH_INFO>(), 4);
    assert_eq!(size_of::<D3DADAPTER_IDENTIFIER9>(), 1104);
    assert_eq!(align_of::<D3DADAPTER_IDENTIFIER9>(), 8);
    assert_eq!(size_of::<D3DRASTER_STATUS>(), 8);
    assert_eq!(align_of::<D3DRASTER_STATUS>(), 4);
    assert_eq!(size_of::<D3DRESOURCESTATS>(), 44);
    assert_eq!(align_of::<D3DRESOURCESTATS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_RESOURCEMANAGER>(), 352);
    assert_eq!(align_of::<D3DDEVINFO_RESOURCEMANAGER>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3DVERTEXSTATS>(), 8);
    assert_eq!(align_of::<D3DDEVINFO_D3DVERTEXSTATS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_VCACHE>(), 16);
    assert_eq!(align_of::<D3DDEVINFO_VCACHE>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9PIPELINETIMINGS>(), 16);
    assert_eq!(align_of::<D3DDEVINFO_D3D9PIPELINETIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9INTERFACETIMINGS>(), 20);
    assert_eq!(align_of::<D3DDEVINFO_D3D9INTERFACETIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9STAGETIMINGS>(), 8);
    assert_eq!(align_of::<D3DDEVINFO_D3D9STAGETIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9BANDWIDTHTIMINGS>(), 20);
    assert_eq!(align_of::<D3DDEVINFO_D3D9BANDWIDTHTIMINGS>(), 4);
    assert_eq!(size_of::<D3DDEVINFO_D3D9CACHEUTILIZATION>(), 8);
    assert_eq!(align_of::<D3DDEVINFO_D3D9CACHEUTILIZATION>(), 4);
    assert_eq!(size_of::<D3DMEMORYPRESSURE>(), 24);
    assert_eq!(align_of::<D3DMEMORYPRESSURE>(), 8);
    assert_eq!(size_of::<D3DCOMPOSERECTDESC>(), 8);
    assert_eq!(align_of::<D3DCOMPOSERECTDESC>(), 2);
    assert_eq!(size_of::<D3DCOMPOSERECTDESTINATION>(), 8);
    assert_eq!(align_of::<D3DCOMPOSERECTDESTINATION>(), 2);
    assert_eq!(size_of::<D3DPRESENTSTATS>(), 32);
    assert_eq!(align_of::<D3DPRESENTSTATS>(), 8);
    assert_eq!(size_of::<D3DDISPLAYMODEEX>(), 24);
    assert_eq!(align_of::<D3DDISPLAYMODEEX>(), 4);
    assert_eq!(size_of::<D3DDISPLAYMODEFILTER>(), 12);
    assert_eq!(align_of::<D3DDISPLAYMODEFILTER>(), 4);
    assert_eq!(size_of::<D3D_OMAC>(), 16);
    assert_eq!(align_of::<D3D_OMAC>(), 1);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERY_INPUT>(), 32);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERY_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERY_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS>(), 4);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS>(), 4);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYPROTECTION_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYPROTECTION_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYCHANNELTYPE_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYCHANNELTYPE_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYDEVICEHANDLE_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYDEVICEHANDLE_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_INPUT>(), 40);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_OUTPUT>(), 72);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYCRYPTOSESSION_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESSCOUNT_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESSCOUNT_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_INPUT>(), 40);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_OUTPUT>(), 64);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYRESTRICTEDSHAREDRESOURCEPROCESS_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNRESTRICTEDPROTECTEDSHAREDRESOURCECOUNT_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNRESTRICTEDPROTECTEDSHAREDRESOURCECOUNT_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_INPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_OUTPUT>(), 72);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTIDCOUNT_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_INPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT>(), 80);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYINFOBUSTYPE_OUTPUT>(), 64);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYINFOBUSTYPE_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUIDCOUNT_OUTPUT>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUIDCOUNT_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_INPUT>(), 40);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_OUTPUT>(), 72);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYEVICTIONENCRYPTIONGUID_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNCOMPRESSEDENCRYPTIONLEVEL_OUTPUT>(), 64);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_QUERYUNCOMPRESSEDENCRYPTIONLEVEL_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_INPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_OUTPUT>(), 48);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURE_OUTPUT>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREINITIALIZE>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREINITIALIZE>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREPROTECTION>(), 56);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREPROTECTION>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURECRYPTOSESSION>(), 72);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURECRYPTOSESSION>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURESHAREDRESOURCE>(), 72);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGURESHAREDRESOURCE>(), 8);
    assert_eq!(size_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREUNCOMPRESSEDENCRYPTION>(), 64);
    assert_eq!(align_of::<D3DAUTHENTICATEDCHANNEL_CONFIGUREUNCOMPRESSEDENCRYPTION>(), 8);
    assert_eq!(size_of::<D3DENCRYPTED_BLOCK_INFO>(), 12);
    assert_eq!(align_of::<D3DENCRYPTED_BLOCK_INFO>(), 4);
    assert_eq!(size_of::<D3DAES_CTR_IV>(), 16);
    assert_eq!(align_of::<D3DAES_CTR_IV>(), 8);
}
#[cfg(all(target_arch = "x86", feature = "guiddef"))] #[test]
fn shared_guiddef() {
    use winapi::shared::guiddef::*;
    assert_eq!(size_of::<GUID>(), 16);
    assert_eq!(align_of::<GUID>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "guiddef"))] #[test]
fn shared_guiddef() {
    use winapi::shared::guiddef::*;
    assert_eq!(size_of::<GUID>(), 16);
    assert_eq!(align_of::<GUID>(), 4);
}
#[cfg(all(target_arch = "x86", feature = "minwindef"))] #[test]
fn shared_minwindef() {
    use winapi::shared::minwindef::*;
    assert_eq!(size_of::<FILETIME>(), 8);
    assert_eq!(align_of::<FILETIME>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "minwindef"))] #[test]
fn shared_minwindef() {
    use winapi::shared::minwindef::*;
    assert_eq!(size_of::<FILETIME>(), 8);
    assert_eq!(align_of::<FILETIME>(), 4);
}
#[cfg(all(target_arch = "x86", feature = "windef"))] #[test]
fn shared_windef() {
    use winapi::shared::windef::*;
    assert_eq!(size_of::<RECT>(), 16);
    assert_eq!(align_of::<RECT>(), 4);
    assert_eq!(size_of::<RECTL>(), 16);
    assert_eq!(align_of::<RECTL>(), 4);
    assert_eq!(size_of::<POINT>(), 8);
    assert_eq!(align_of::<POINT>(), 4);
    assert_eq!(size_of::<POINTL>(), 8);
    assert_eq!(align_of::<POINTL>(), 4);
    assert_eq!(size_of::<SIZE>(), 8);
    assert_eq!(align_of::<SIZE>(), 4);
    assert_eq!(size_of::<POINTS>(), 4);
    assert_eq!(align_of::<POINTS>(), 2);
}
#[cfg(all(target_arch = "x86_64", feature = "windef"))] #[test]
fn shared_windef() {
    use winapi::shared::windef::*;
    assert_eq!(size_of::<RECT>(), 16);
    assert_eq!(align_of::<RECT>(), 4);
    assert_eq!(size_of::<RECTL>(), 16);
    assert_eq!(align_of::<RECTL>(), 4);
    assert_eq!(size_of::<POINT>(), 8);
    assert_eq!(align_of::<POINT>(), 4);
    assert_eq!(size_of::<POINTL>(), 8);
    assert_eq!(align_of::<POINTL>(), 4);
    assert_eq!(size_of::<SIZE>(), 8);
    assert_eq!(align_of::<SIZE>(), 4);
    assert_eq!(size_of::<POINTS>(), 4);
    assert_eq!(align_of::<POINTS>(), 2);
}
#[cfg(all(target_arch = "x86", feature = "wininet"))] #[test]
fn um_wininet() {
    use winapi::um::wininet::*;
    assert_eq!(size_of::<INTERNET_ASYNC_RESULT>(), 8);
    assert_eq!(align_of::<INTERNET_ASYNC_RESULT>(), 4);
    assert_eq!(size_of::<INTERNET_DIAGNOSTIC_SOCKET_INFO>(), 16);
    assert_eq!(align_of::<INTERNET_DIAGNOSTIC_SOCKET_INFO>(), 4);
    assert_eq!(size_of::<INTERNET_PROXY_INFO>(), 12);
    assert_eq!(align_of::<INTERNET_PROXY_INFO>(), 4);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONA>(), 12);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONA>(), 4);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONA>(), 12);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONA>(), 4);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONW>(), 12);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONW>(), 4);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONW>(), 12);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONW>(), 4);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTION_LISTA>(), 20);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTION_LISTA>(), 4);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTION_LISTW>(), 20);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTION_LISTW>(), 4);
    assert_eq!(size_of::<INTERNET_VERSION_INFO>(), 8);
    assert_eq!(align_of::<INTERNET_VERSION_INFO>(), 4);
    assert_eq!(size_of::<HTTP_VERSION_INFO>(), 8);
    assert_eq!(align_of::<HTTP_VERSION_INFO>(), 4);
    assert_eq!(size_of::<INTERNET_CONNECTED_INFO>(), 8);
    assert_eq!(align_of::<INTERNET_CONNECTED_INFO>(), 4);
    assert_eq!(size_of::<URL_COMPONENTSA>(), 60);
    assert_eq!(align_of::<URL_COMPONENTSA>(), 4);
    assert_eq!(size_of::<URL_COMPONENTSW>(), 60);
    assert_eq!(align_of::<URL_COMPONENTSW>(), 4);
    assert_eq!(size_of::<INTERNET_CERTIFICATE_INFO>(), 40);
    assert_eq!(align_of::<INTERNET_CERTIFICATE_INFO>(), 4);
    assert_eq!(size_of::<INTERNET_BUFFERSA>(), 40);
    assert_eq!(align_of::<INTERNET_BUFFERSA>(), 4);
    assert_eq!(size_of::<INTERNET_BUFFERSW>(), 40);
    assert_eq!(align_of::<INTERNET_BUFFERSW>(), 4);
    assert_eq!(size_of::<IncomingCookieState>(), 28);
    assert_eq!(align_of::<IncomingCookieState>(), 4);
    assert_eq!(size_of::<OutgoingCookieState>(), 12);
    assert_eq!(align_of::<OutgoingCookieState>(), 4);
    assert_eq!(size_of::<InternetCookieHistory>(), 16);
    assert_eq!(align_of::<InternetCookieHistory>(), 4);
    assert_eq!(size_of::<CookieDecision>(), 8);
    assert_eq!(align_of::<CookieDecision>(), 4);
    assert_eq!(size_of::<GOPHER_FIND_DATAA>(), 808);
    assert_eq!(align_of::<GOPHER_FIND_DATAA>(), 4);
    assert_eq!(size_of::<GOPHER_FIND_DATAW>(), 1588);
    assert_eq!(align_of::<GOPHER_FIND_DATAW>(), 4);
    assert_eq!(size_of::<GOPHER_ADMIN_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_ADMIN_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_MOD_DATE_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_MOD_DATE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_TTL_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_TTL_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_SCORE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_SCORE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_SITE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_SITE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_ORGANIZATION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_ORGANIZATION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_LOCATION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_LOCATION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE>(), 24);
    assert_eq!(align_of::<GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_TIMEZONE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_TIMEZONE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_PROVIDER_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_PROVIDER_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_VERSION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_VERSION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_ABSTRACT_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_ABSTRACT_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_VIEW_ATTRIBUTE_TYPE>(), 12);
    assert_eq!(align_of::<GOPHER_VIEW_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_VERONICA_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_VERONICA_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_ASK_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_ASK_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_UNKNOWN_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_UNKNOWN_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_ATTRIBUTE_TYPE>(), 32); // FIXME
    assert_eq!(align_of::<GOPHER_ATTRIBUTE_TYPE>(), 4); // FIXME
    assert_eq!(size_of::<INTERNET_COOKIE2>(), 32);
    assert_eq!(align_of::<INTERNET_COOKIE2>(), 4);
    assert_eq!(size_of::<INTERNET_AUTH_NOTIFY_DATA>(), 16);
    assert_eq!(align_of::<INTERNET_AUTH_NOTIFY_DATA>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_ENTRY_INFOA>(), 80);
    assert_eq!(align_of::<INTERNET_CACHE_ENTRY_INFOA>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_ENTRY_INFOW>(), 80);
    assert_eq!(align_of::<INTERNET_CACHE_ENTRY_INFOW>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_TIMESTAMPS>(), 16);
    assert_eq!(align_of::<INTERNET_CACHE_TIMESTAMPS>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_GROUP_INFOA>(), 156);
    assert_eq!(align_of::<INTERNET_CACHE_GROUP_INFOA>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_GROUP_INFOW>(), 276);
    assert_eq!(align_of::<INTERNET_CACHE_GROUP_INFOW>(), 4);
    assert_eq!(size_of::<AutoProxyHelperVtbl>(), 36);
    assert_eq!(align_of::<AutoProxyHelperVtbl>(), 4);
    assert_eq!(size_of::<AUTO_PROXY_SCRIPT_BUFFER>(), 12);
    assert_eq!(align_of::<AUTO_PROXY_SCRIPT_BUFFER>(), 4);
    assert_eq!(size_of::<AutoProxyHelperFunctions>(), 4);
    assert_eq!(align_of::<AutoProxyHelperFunctions>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "wininet"))] #[test]
fn um_wininet() {
    use winapi::um::wininet::*;
    assert_eq!(size_of::<INTERNET_ASYNC_RESULT>(), 16);
    assert_eq!(align_of::<INTERNET_ASYNC_RESULT>(), 8);
    assert_eq!(size_of::<INTERNET_DIAGNOSTIC_SOCKET_INFO>(), 24);
    assert_eq!(align_of::<INTERNET_DIAGNOSTIC_SOCKET_INFO>(), 8);
    assert_eq!(size_of::<INTERNET_PROXY_INFO>(), 24);
    assert_eq!(align_of::<INTERNET_PROXY_INFO>(), 8);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONA>(), 16);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONA>(), 8);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONA>(), 16);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONA>(), 8);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONW>(), 16);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONW>(), 8);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTIONW>(), 16);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTIONW>(), 8);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTION_LISTA>(), 32);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTION_LISTA>(), 8);
    assert_eq!(size_of::<INTERNET_PER_CONN_OPTION_LISTW>(), 32);
    assert_eq!(align_of::<INTERNET_PER_CONN_OPTION_LISTW>(), 8);
    assert_eq!(size_of::<INTERNET_VERSION_INFO>(), 8);
    assert_eq!(align_of::<INTERNET_VERSION_INFO>(), 4);
    assert_eq!(size_of::<HTTP_VERSION_INFO>(), 8);
    assert_eq!(align_of::<HTTP_VERSION_INFO>(), 4);
    assert_eq!(size_of::<INTERNET_CONNECTED_INFO>(), 8);
    assert_eq!(align_of::<INTERNET_CONNECTED_INFO>(), 4);
    assert_eq!(size_of::<URL_COMPONENTSA>(), 104);
    assert_eq!(align_of::<URL_COMPONENTSA>(), 8);
    assert_eq!(size_of::<URL_COMPONENTSW>(), 104);
    assert_eq!(align_of::<URL_COMPONENTSW>(), 8);
    assert_eq!(size_of::<INTERNET_CERTIFICATE_INFO>(), 64);
    assert_eq!(align_of::<INTERNET_CERTIFICATE_INFO>(), 8);
    assert_eq!(size_of::<INTERNET_BUFFERSA>(), 56);
    assert_eq!(align_of::<INTERNET_BUFFERSA>(), 8);
    assert_eq!(size_of::<INTERNET_BUFFERSW>(), 56);
    assert_eq!(align_of::<INTERNET_BUFFERSW>(), 8);
    assert_eq!(size_of::<IncomingCookieState>(), 32);
    assert_eq!(align_of::<IncomingCookieState>(), 8);
    assert_eq!(size_of::<OutgoingCookieState>(), 16);
    assert_eq!(align_of::<OutgoingCookieState>(), 8);
    assert_eq!(size_of::<InternetCookieHistory>(), 16);
    assert_eq!(align_of::<InternetCookieHistory>(), 4);
    assert_eq!(size_of::<CookieDecision>(), 8);
    assert_eq!(align_of::<CookieDecision>(), 4);
    assert_eq!(size_of::<GOPHER_FIND_DATAA>(), 808);
    assert_eq!(align_of::<GOPHER_FIND_DATAA>(), 4);
    assert_eq!(size_of::<GOPHER_FIND_DATAW>(), 1588);
    assert_eq!(align_of::<GOPHER_FIND_DATAW>(), 4);
    assert_eq!(size_of::<GOPHER_ADMIN_ATTRIBUTE_TYPE>(), 16);
    assert_eq!(align_of::<GOPHER_ADMIN_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_MOD_DATE_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_MOD_DATE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_TTL_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_TTL_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_SCORE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_SCORE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_SITE_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_SITE_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_ORGANIZATION_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_ORGANIZATION_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_LOCATION_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_LOCATION_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE>(), 24);
    assert_eq!(align_of::<GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_TIMEZONE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_TIMEZONE_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_PROVIDER_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_PROVIDER_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_VERSION_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_VERSION_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_ABSTRACT_ATTRIBUTE_TYPE>(), 16);
    assert_eq!(align_of::<GOPHER_ABSTRACT_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_VIEW_ATTRIBUTE_TYPE>(), 24);
    assert_eq!(align_of::<GOPHER_VIEW_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_VERONICA_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(align_of::<GOPHER_VERONICA_ATTRIBUTE_TYPE>(), 4);
    assert_eq!(size_of::<GOPHER_ASK_ATTRIBUTE_TYPE>(), 16);
    assert_eq!(align_of::<GOPHER_ASK_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_UNKNOWN_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(align_of::<GOPHER_UNKNOWN_ATTRIBUTE_TYPE>(), 8);
    assert_eq!(size_of::<GOPHER_ATTRIBUTE_TYPE>(), 32); // FIXME
    assert_eq!(align_of::<GOPHER_ATTRIBUTE_TYPE>(), 8); // FIXME
    assert_eq!(size_of::<INTERNET_COOKIE2>(), 48);
    assert_eq!(align_of::<INTERNET_COOKIE2>(), 8);
    assert_eq!(size_of::<INTERNET_AUTH_NOTIFY_DATA>(), 24);
    assert_eq!(align_of::<INTERNET_AUTH_NOTIFY_DATA>(), 8);
    assert_eq!(size_of::<INTERNET_CACHE_ENTRY_INFOA>(), 112);
    assert_eq!(align_of::<INTERNET_CACHE_ENTRY_INFOA>(), 8);
    assert_eq!(size_of::<INTERNET_CACHE_ENTRY_INFOW>(), 112);
    assert_eq!(align_of::<INTERNET_CACHE_ENTRY_INFOW>(), 8);
    assert_eq!(size_of::<INTERNET_CACHE_TIMESTAMPS>(), 16);
    assert_eq!(align_of::<INTERNET_CACHE_TIMESTAMPS>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_GROUP_INFOA>(), 156);
    assert_eq!(align_of::<INTERNET_CACHE_GROUP_INFOA>(), 4);
    assert_eq!(size_of::<INTERNET_CACHE_GROUP_INFOW>(), 276);
    assert_eq!(align_of::<INTERNET_CACHE_GROUP_INFOW>(), 4);
    assert_eq!(size_of::<AutoProxyHelperVtbl>(), 72);
    assert_eq!(align_of::<AutoProxyHelperVtbl>(), 8);
    assert_eq!(size_of::<AUTO_PROXY_SCRIPT_BUFFER>(), 24);
    assert_eq!(align_of::<AUTO_PROXY_SCRIPT_BUFFER>(), 8);
    assert_eq!(size_of::<AutoProxyHelperFunctions>(), 8);
    assert_eq!(align_of::<AutoProxyHelperFunctions>(), 8);
}
#[cfg(all(target_arch = "x86", feature = "wtypesbase"))] #[test]
fn shared_wtypesbase() {
    use winapi::shared::wtypesbase::*;
    assert_eq!(size_of::<COAUTHIDENTITY>(), 28);
    assert_eq!(align_of::<COAUTHIDENTITY>(), 4);
    assert_eq!(size_of::<COAUTHINFO>(), 28);
    assert_eq!(align_of::<COAUTHINFO>(), 4);
    assert_eq!(size_of::<BYTE_BLOB>(), 8);
    assert_eq!(align_of::<BYTE_BLOB>(), 4);
    assert_eq!(size_of::<WORD_BLOB>(), 8);
    assert_eq!(align_of::<WORD_BLOB>(), 4);
    assert_eq!(size_of::<WORD_BLOB>(), 8);
    assert_eq!(align_of::<WORD_BLOB>(), 4);
    assert_eq!(size_of::<FLAGGED_BYTE_BLOB>(), 12);
    assert_eq!(align_of::<FLAGGED_BYTE_BLOB>(), 4);
    assert_eq!(size_of::<FLAGGED_WORD_BLOB>(), 12);
    assert_eq!(align_of::<FLAGGED_WORD_BLOB>(), 4);
    assert_eq!(size_of::<BYTE_SIZEDARR>(), 8);
    assert_eq!(align_of::<BYTE_SIZEDARR>(), 4);
    assert_eq!(size_of::<WORD_SIZEDARR>(), 8);
    assert_eq!(align_of::<WORD_SIZEDARR>(), 4);
    assert_eq!(size_of::<DWORD_SIZEDARR>(), 8);
    assert_eq!(align_of::<DWORD_SIZEDARR>(), 4);
    assert_eq!(size_of::<HYPER_SIZEDARR>(), 8);
    assert_eq!(align_of::<HYPER_SIZEDARR>(), 4);
    assert_eq!(size_of::<BLOB>(), 8);
    assert_eq!(align_of::<BLOB>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "wtypesbase"))] #[test]
fn shared_wtypesbase() {
    use winapi::shared::wtypesbase::*;
    assert_eq!(size_of::<COAUTHIDENTITY>(), 48);
    assert_eq!(align_of::<COAUTHIDENTITY>(), 8);
    assert_eq!(size_of::<COAUTHINFO>(), 40);
    assert_eq!(align_of::<COAUTHINFO>(), 8);
    assert_eq!(size_of::<BYTE_BLOB>(), 8);
    assert_eq!(align_of::<BYTE_BLOB>(), 4);
    assert_eq!(size_of::<WORD_BLOB>(), 8);
    assert_eq!(align_of::<WORD_BLOB>(), 4);
    assert_eq!(size_of::<WORD_BLOB>(), 8);
    assert_eq!(align_of::<WORD_BLOB>(), 4);
    assert_eq!(size_of::<FLAGGED_BYTE_BLOB>(), 12);
    assert_eq!(align_of::<FLAGGED_BYTE_BLOB>(), 4);
    assert_eq!(size_of::<FLAGGED_WORD_BLOB>(), 12);
    assert_eq!(align_of::<FLAGGED_WORD_BLOB>(), 4);
    assert_eq!(size_of::<BYTE_SIZEDARR>(), 16);
    assert_eq!(align_of::<BYTE_SIZEDARR>(), 8);
    assert_eq!(size_of::<WORD_SIZEDARR>(), 16);
    assert_eq!(align_of::<WORD_SIZEDARR>(), 8);
    assert_eq!(size_of::<DWORD_SIZEDARR>(), 16);
    assert_eq!(align_of::<DWORD_SIZEDARR>(), 8);
    assert_eq!(size_of::<HYPER_SIZEDARR>(), 16);
    assert_eq!(align_of::<HYPER_SIZEDARR>(), 8);
    assert_eq!(size_of::<BLOB>(), 16);
    assert_eq!(align_of::<BLOB>(), 8);
}
#[cfg(all(target_arch = "x86", feature = "shellapi"))] #[test]
fn um_shellapi() {
    use winapi::um::shellapi::*;
    assert_eq!(size_of::<DRAGINFOA>(), 24);
    assert_eq!(align_of::<DRAGINFOA>(), 1);
    assert_eq!(size_of::<DRAGINFOW>(), 24);
    assert_eq!(align_of::<DRAGINFOW>(), 1);
    assert_eq!(size_of::<APPBARDATA>(), 36);
    assert_eq!(align_of::<APPBARDATA>(), 1);
    assert_eq!(size_of::<SHFILEOPSTRUCTA>(), 30);
    assert_eq!(align_of::<SHFILEOPSTRUCTA>(), 1);
    assert_eq!(size_of::<SHFILEOPSTRUCTW>(), 30);
    assert_eq!(align_of::<SHFILEOPSTRUCTW>(), 1);
    assert_eq!(size_of::<SHNAMEMAPPINGA>(), 16);
    assert_eq!(align_of::<SHNAMEMAPPINGA>(), 1);
    assert_eq!(size_of::<SHNAMEMAPPINGW>(), 16);
    assert_eq!(align_of::<SHNAMEMAPPINGW>(), 1);
    assert_eq!(size_of::<SHELLEXECUTEINFOA>(), 60);
    assert_eq!(align_of::<SHELLEXECUTEINFOA>(), 1);
    assert_eq!(size_of::<SHELLEXECUTEINFOW>(), 60);
    assert_eq!(align_of::<SHELLEXECUTEINFOW>(), 1);
    assert_eq!(size_of::<SHCREATEPROCESSINFOW>(), 52);
    assert_eq!(align_of::<SHCREATEPROCESSINFOW>(), 1);
    assert_eq!(size_of::<ASSOCIATIONELEMENT>(), 12);
    assert_eq!(align_of::<ASSOCIATIONELEMENT>(), 1);
    assert_eq!(size_of::<SHQUERYRBINFO>(), 20);
    assert_eq!(align_of::<SHQUERYRBINFO>(), 1);
    assert_eq!(size_of::<NOTIFYICONDATAA>(), 508);
    assert_eq!(align_of::<NOTIFYICONDATAA>(), 1);
    assert_eq!(size_of::<NOTIFYICONDATAW>(), 956);
    assert_eq!(align_of::<NOTIFYICONDATAW>(), 1);
    assert_eq!(size_of::<NOTIFYICONIDENTIFIER>(), 28);
    assert_eq!(align_of::<NOTIFYICONIDENTIFIER>(), 1);
    assert_eq!(size_of::<SHFILEINFOA>(), 352);
    assert_eq!(align_of::<SHFILEINFOA>(), 1);
    assert_eq!(size_of::<SHFILEINFOW>(), 692);
    assert_eq!(align_of::<SHFILEINFOW>(), 1);
    assert_eq!(size_of::<SHSTOCKICONINFO>(), 536);
    assert_eq!(align_of::<SHSTOCKICONINFO>(), 1);
    assert_eq!(size_of::<OPEN_PRINTER_PROPS_INFOA>(), 20);
    assert_eq!(align_of::<OPEN_PRINTER_PROPS_INFOA>(), 1);
    assert_eq!(size_of::<OPEN_PRINTER_PROPS_INFOW>(), 20);
    assert_eq!(align_of::<OPEN_PRINTER_PROPS_INFOW>(), 1);
    // assert_eq!(size_of::<NC_ADDRESS>(), 8);
    // assert_eq!(align_of::<NC_ADDRESS>(), 4);
}
#[cfg(all(target_arch = "x86_64", feature = "shellapi"))] #[test]
fn um_shellapi() {
    use winapi::um::shellapi::*;
    assert_eq!(size_of::<DRAGINFOA>(), 32);
    assert_eq!(align_of::<DRAGINFOA>(), 8);
    assert_eq!(size_of::<DRAGINFOW>(), 32);
    assert_eq!(align_of::<DRAGINFOW>(), 8);
    assert_eq!(size_of::<APPBARDATA>(), 48);
    assert_eq!(align_of::<APPBARDATA>(), 8);
    assert_eq!(size_of::<SHFILEOPSTRUCTA>(), 56);
    assert_eq!(align_of::<SHFILEOPSTRUCTA>(), 8);
    assert_eq!(size_of::<SHFILEOPSTRUCTW>(), 56);
    assert_eq!(align_of::<SHFILEOPSTRUCTW>(), 8);
    assert_eq!(size_of::<SHNAMEMAPPINGA>(), 24);
    assert_eq!(align_of::<SHNAMEMAPPINGA>(), 8);
    assert_eq!(size_of::<SHNAMEMAPPINGW>(), 24);
    assert_eq!(align_of::<SHNAMEMAPPINGW>(), 8);
    assert_eq!(size_of::<SHELLEXECUTEINFOA>(), 112);
    assert_eq!(align_of::<SHELLEXECUTEINFOA>(), 8);
    assert_eq!(size_of::<SHELLEXECUTEINFOW>(), 112);
    assert_eq!(align_of::<SHELLEXECUTEINFOW>(), 8);
    assert_eq!(size_of::<SHCREATEPROCESSINFOW>(), 88);
    assert_eq!(align_of::<SHCREATEPROCESSINFOW>(), 8);
    assert_eq!(size_of::<ASSOCIATIONELEMENT>(), 24);
    assert_eq!(align_of::<ASSOCIATIONELEMENT>(), 8);
    assert_eq!(size_of::<SHQUERYRBINFO>(), 24);
    assert_eq!(align_of::<SHQUERYRBINFO>(), 8);
    assert_eq!(size_of::<NOTIFYICONDATAA>(), 528);
    assert_eq!(align_of::<NOTIFYICONDATAA>(), 8);
    assert_eq!(size_of::<NOTIFYICONDATAW>(), 976);
    assert_eq!(align_of::<NOTIFYICONDATAW>(), 8);
    assert_eq!(size_of::<NOTIFYICONIDENTIFIER>(), 40);
    assert_eq!(align_of::<NOTIFYICONIDENTIFIER>(), 8);
    assert_eq!(size_of::<SHFILEINFOA>(), 360);
    assert_eq!(align_of::<SHFILEINFOA>(), 8);
    assert_eq!(size_of::<SHFILEINFOW>(), 696);
    assert_eq!(align_of::<SHFILEINFOW>(), 8);
    assert_eq!(size_of::<SHSTOCKICONINFO>(), 544);
    assert_eq!(align_of::<SHSTOCKICONINFO>(), 8);
    assert_eq!(size_of::<OPEN_PRINTER_PROPS_INFOA>(), 32);
    assert_eq!(align_of::<OPEN_PRINTER_PROPS_INFOA>(), 8);
    assert_eq!(size_of::<OPEN_PRINTER_PROPS_INFOW>(), 32);
    assert_eq!(align_of::<OPEN_PRINTER_PROPS_INFOW>(), 8);
    // assert_eq!(size_of::<NC_ADDRESS>(), 16);
    // assert_eq!(align_of::<NC_ADDRESS>(), 8);
}
