// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// All files in the project carrying such notice may not be copied, modified, or distributed
// except according to those terms.
//! SAPI 5.4 definitions
use shared::guiddef::GUID;
use shared::minwindef::{BYTE, ULONG, WORD};
pub use um::sapi53::{
    IEnumSpObjectTokens, IEnumSpObjectTokensVtbl, ISpDataKey, ISpDataKeyVtbl, ISpNotifyCallback,
    ISpNotifySink, ISpNotifySinkVtbl, ISpNotifySource, ISpNotifySourceVtbl, ISpNotifyTranslator,
    ISpNotifyTranslatorVtbl, ISpObjectToken, ISpObjectTokenCategory, ISpObjectTokenCategoryVtbl,
    ISpObjectTokenInit, ISpObjectTokenInitVtbl, ISpObjectTokenVtbl, ISpObjectWithToken,
    ISpObjectWithTokenVtbl, ISpRegDataKey, ISpRegDataKeyVtbl, ISpResourceManager,
    ISpResourceManagerVtbl, SPDFID_Text, SPDFID_WaveFormatEx, SPDKL_CurrentConfig,
    SPDKL_CurrentUser, SPDKL_DefaultLocation, SPDKL_LocalMachine, SPDUI_AddRemoveWord,
    SPDUI_AudioProperties, SPDUI_AudioVolume, SPDUI_EngineProperties, SPDUI_MicTraining,
    SPDUI_RecoProfileProperties, SPDUI_ShareData, SPDUI_Tutorial, SPDUI_UserEnrollment,
    SPDUI_UserTraining, SPSF_11kHz16BitMono, SPSF_11kHz16BitStereo, SPSF_11kHz8BitMono,
    SPSF_11kHz8BitStereo, SPSF_12kHz16BitMono, SPSF_12kHz16BitStereo, SPSF_12kHz8BitMono,
    SPSF_12kHz8BitStereo, SPSF_16kHz16BitMono, SPSF_16kHz16BitStereo, SPSF_16kHz8BitMono,
    SPSF_16kHz8BitStereo, SPSF_22kHz16BitMono, SPSF_22kHz16BitStereo, SPSF_22kHz8BitMono,
    SPSF_22kHz8BitStereo, SPSF_24kHz16BitMono, SPSF_24kHz16BitStereo, SPSF_24kHz8BitMono,
    SPSF_24kHz8BitStereo, SPSF_32kHz16BitMono, SPSF_32kHz16BitStereo, SPSF_32kHz8BitMono,
    SPSF_32kHz8BitStereo, SPSF_44kHz16BitMono, SPSF_44kHz16BitStereo, SPSF_44kHz8BitMono,
    SPSF_44kHz8BitStereo, SPSF_48kHz16BitMono, SPSF_48kHz16BitStereo, SPSF_48kHz8BitMono,
    SPSF_48kHz8BitStereo, SPSF_8kHz16BitMono, SPSF_8kHz16BitStereo, SPSF_8kHz8BitMono,
    SPSF_8kHz8BitStereo, SPSF_ADPCM_11kHzMono, SPSF_ADPCM_11kHzStereo, SPSF_ADPCM_22kHzMono,
    SPSF_ADPCM_22kHzStereo, SPSF_ADPCM_44kHzMono, SPSF_ADPCM_44kHzStereo, SPSF_ADPCM_8kHzMono,
    SPSF_ADPCM_8kHzStereo, SPSF_CCITT_ALaw_11kHzMono, SPSF_CCITT_ALaw_11kHzStereo,
    SPSF_CCITT_ALaw_22kHzMono, SPSF_CCITT_ALaw_22kHzStereo, SPSF_CCITT_ALaw_44kHzMono,
    SPSF_CCITT_ALaw_44kHzStereo, SPSF_CCITT_ALaw_8kHzMono, SPSF_CCITT_ALaw_8kHzStereo,
    SPSF_CCITT_uLaw_11kHzMono, SPSF_CCITT_uLaw_11kHzStereo, SPSF_CCITT_uLaw_22kHzMono,
    SPSF_CCITT_uLaw_22kHzStereo, SPSF_CCITT_uLaw_44kHzMono, SPSF_CCITT_uLaw_44kHzStereo,
    SPSF_CCITT_uLaw_8kHzMono, SPSF_CCITT_uLaw_8kHzStereo, SPSF_Default, SPSF_ExtendedAudioFormat,
    SPSF_GSM610_11kHzMono, SPSF_GSM610_22kHzMono, SPSF_GSM610_44kHzMono, SPSF_GSM610_8kHzMono,
    SPSF_NoAssignedFormat, SPSF_NonStandardFormat, SPSF_Text, SPSF_TrueSpeech_8kHz1BitMono,
    DEFAULT_WEIGHT, SPCAT_APPLEXICONS, SPCAT_AUDIOIN, SPCAT_AUDIOOUT, SPCAT_PHONECONVERTERS,
    SPCAT_RECOGNIZERS, SPCAT_RECOPROFILES, SPCAT_TEXTNORMALIZERS, SPCAT_VOICES,
    SPCURRENT_USER_LEXICON_TOKEN_ID, SPDATAKEYLOCATION, SPDICTATION, SPEI_ADAPTATION,
    SPEI_END_INPUT_STREAM, SPEI_END_SR_STREAM, SPEI_FALSE_RECOGNITION, SPEI_HYPOTHESIS,
    SPEI_INTERFERENCE, SPEI_MAX_TTS, SPEI_MIN_TTS, SPEI_PHONEME, SPEI_PHRASE_START,
    SPEI_PROPERTY_NUM_CHANGE, SPEI_PROPERTY_STRING_CHANGE, SPEI_RECOGNITION,
    SPEI_RECO_OTHER_CONTEXT, SPEI_RECO_STATE_CHANGE, SPEI_REQUEST_UI, SPEI_SENTENCE_BOUNDARY,
    SPEI_SOUND_END, SPEI_SOUND_START, SPEI_SR_AUDIO_LEVEL, SPEI_SR_BOOKMARK, SPEI_SR_PRIVATE,
    SPEI_SR_RETAINEDAUDIO, SPEI_START_INPUT_STREAM, SPEI_START_SR_STREAM, SPEI_TTS_AUDIO_LEVEL,
    SPEI_TTS_BOOKMARK, SPEI_TTS_PRIVATE, SPEI_UNDEFINED, SPEI_VISEME, SPEI_VOICE_CHANGE,
    SPEI_WORD_BOUNDARY, SPET_LPARAM_IS_OBJECT, SPET_LPARAM_IS_POINTER, SPET_LPARAM_IS_STRING,
    SPET_LPARAM_IS_TOKEN, SPET_LPARAM_IS_UNDEFINED, SPEVENTENUM, SPEVENTLPARAMTYPE, SPINFDICTATION,
    SPMMSYS_AUDIO_IN_TOKEN_ID, SPMMSYS_AUDIO_OUT_TOKEN_ID, SPNOTIFYCALLBACK, SPPROP_ADAPTATION_ON,
    SPPROP_COMPLEX_RESPONSE_SPEED, SPPROP_HIGH_CONFIDENCE_THRESHOLD,
    SPPROP_LOW_CONFIDENCE_THRESHOLD, SPPROP_NORMAL_CONFIDENCE_THRESHOLD,
    SPPROP_PERSISTED_BACKGROUND_ADAPTATION, SPPROP_PERSISTED_LANGUAGE_MODEL_ADAPTATION,
    SPPROP_RESOURCE_USAGE, SPPROP_RESPONSE_SPEED, SPPROP_UX_IS_LISTENING, SPREG_LOCAL_MACHINE_ROOT,
    SPREG_SAFE_USER_TOKENS, SPREG_USER_ROOT, SPSF_NUM_FORMATS, SPSTREAMFORMAT,
    SPTOKENKEY_ATTRIBUTES, SPTOKENKEY_AUDIO_LATENCY_TRUNCATE,
    SPTOKENKEY_AUDIO_LATENCY_UPDATE_INTERVAL, SPTOKENKEY_AUDIO_LATENCY_WARNING, SPTOKENKEY_FILES,
    SPTOKENKEY_RETAINEDAUDIO, SPTOKENKEY_UI, SPTOKENVALUE_CLSID, SPTOPIC_SPELLING,
    SPVOICECATEGORY_TTSRATE, SPWILDCARD, SP_EMULATE_RESULT, SP_HIGH_CONFIDENCE, SP_LOW_CONFIDENCE,
    SP_MAX_PRON_LENGTH, SP_MAX_WORD_LENGTH, SP_NORMAL_CONFIDENCE,
};
use um::unknwnbase::{IUnknown, IUnknownVtbl};
use um::winnt::{HRESULT, LPWSTR, ULONGLONG};
pub const ACTIVE_CATEGORY_CHANGED: SPEVENTENUM = 53;
pub use um::sapi53::SPPHRASE as SPPHRASE_53;
pub use um::sapi53::{
    ISpAudio,
    ISpAudioVtbl,
    ISpEventSink,
    ISpEventSinkVtbl,
    ISpEventSource,
    ISpEventSource2,
    ISpEventSource2Vtbl,
    ISpEventSourceVtbl,
    ISpMMSysAudio,
    ISpMMSysAudioVtbl,
    ISpStream,
    ISpStreamFormat,
    ISpStreamFormatConverter,
    ISpStreamFormatConverterVtbl,
    ISpStreamFormatVtbl,
    ISpStreamVtbl,
    ISpTranscript,
    ISpTranscriptVtbl,
    PCSPPHONEID,
    PSPPHONEID,
    SPAF_ALL,
    SPAF_BUFFER_POSITION,
    SPAF_CONSUME_LEADING_SPACES,
    SPAF_ONE_TRAILING_SPACE,
    SPAF_TWO_TRAILING_SPACES,
    SPAF_USER_SPECIFIED,
    SPAS_CLOSED,
    SPAS_PAUSE,
    SPAS_RUN,
    SPAS_STOP,
    SPAUDIOBUFFERINFO,
    SPAUDIOSTATE,
    SPAUDIOSTATUS,
    SPDISPLAYATTRIBUTES,
    SPEI_MAX_SR,
    SPEI_MIN_SR,
    SPEI_RESERVED1,
    SPEI_RESERVED2,
    SPEI_RESERVED3,
    SPEI_RESERVED5,
    SPEI_RESERVED6,
    SPENDSRSTREAMFLAGS,
    SPESF_EMULATED,
    SPESF_NONE,
    SPESF_STREAM_RELEASED,
    SPEVENT,
    SPEVENTEX,
    SPEVENTSOURCEINFO,
    SPFEI,
    SPFEI_ALL_EVENTS,
    SPFEI_ALL_SR_EVENTS,
    SPFEI_ALL_TTS_EVENTS,
    SPFEI_FLAGCHECK,
    SPFILEMODE,
    SPFM_CREATE,
    SPFM_CREATE_ALWAYS,
    SPFM_NUM_MODES,
    SPFM_OPEN_READONLY,
    SPFM_OPEN_READWRITE,
    SPINTERFERENCE,
    SPINTERFERENCE_LATENCY_TRUNCATE_BEGIN,
    SPINTERFERENCE_LATENCY_TRUNCATE_END,
    SPINTERFERENCE_LATENCY_WARNING,
    SPINTERFERENCE_NOISE,
    SPINTERFERENCE_NONE,
    SPINTERFERENCE_NOSIGNAL,
    SPINTERFERENCE_TOOFAST,
    SPINTERFERENCE_TOOLOUD,
    SPINTERFERENCE_TOOQUIET,
    SPINTERFERENCE_TOOSLOW,
    SPPHONEID,
    SPPHRASEELEMENT,
    SPPHRASEPROPERTY,
    SPPHRASEPROPERTYUNIONTYPE,
    SPPHRASEREPLACEMENT,
    SPPHRASERULE,
    SPPHRASE_50,
    // SPPHRASESIZE_500,
    SPPPUT_ARRAY_INDEX,
    SPPPUT_UNUSED,
    SPSEMANTICERRORINFO,
    SPSEMANTICFORMAT,
    SPSERIALIZEDEVENT,
    SPSERIALIZEDEVENT64,
    SPVFEATURE,
    SPVFEATURE_EMPHASIS,
    SPVFEATURE_STRESSED,
    SPVISEMES,
    SP_VISEME_0,
    SP_VISEME_1,
    SP_VISEME_10,
    SP_VISEME_11,
    SP_VISEME_12,
    SP_VISEME_13,
    SP_VISEME_14,
    SP_VISEME_15,
    SP_VISEME_16,
    SP_VISEME_17,
    SP_VISEME_18,
    SP_VISEME_19,
    SP_VISEME_2,
    SP_VISEME_20,
    SP_VISEME_21,
    SP_VISEME_3,
    SP_VISEME_4,
    SP_VISEME_5,
    SP_VISEME_6,
    SP_VISEME_7,
    SP_VISEME_8,
    SP_VISEME_9,
};
STRUCT! {struct SPPHRASE {
    cbSize: ULONG,
    LangID: WORD,
    wHomophoneGroupId: WORD,
    ullGrammarID: ULONGLONG,
    ftStartTime: ULONGLONG,
    ullAudioStreamPosition: ULONGLONG,
    ulAudioSizeBytes: ULONG,
    ulRetainedSizeBytes: ULONG,
    ulAudioSizeTime: ULONG,
    Rule: SPPHRASERULE,
    pProperties: *const SPPHRASEPROPERTY,
    pElements: *const SPPHRASEELEMENT,
    cReplacements: ULONG,
    pReplacements: *const SPPHRASEREPLACEMENT,
    SREngineID: GUID,
    ulSREnginePrivateDataSize: ULONG,
    pSREnginePrivateData: *const BYTE,
    pSML: LPWSTR,
    pSemanticErrorInfo: *mut SPSEMANTICERRORINFO,
    SemanticTagFormat: SPSEMANTICFORMAT,
}}
pub use um::sapi53::{
    eLEXTYPE_APP, eLEXTYPE_LETTERTOSOUND, eLEXTYPE_MORPHOLOGY, eLEXTYPE_PRIVATE1,
    eLEXTYPE_PRIVATE10, eLEXTYPE_PRIVATE11, eLEXTYPE_PRIVATE12, eLEXTYPE_PRIVATE13,
    eLEXTYPE_PRIVATE14, eLEXTYPE_PRIVATE15, eLEXTYPE_PRIVATE16, eLEXTYPE_PRIVATE17,
    eLEXTYPE_PRIVATE18, eLEXTYPE_PRIVATE19, eLEXTYPE_PRIVATE2, eLEXTYPE_PRIVATE20,
    eLEXTYPE_PRIVATE3, eLEXTYPE_PRIVATE4, eLEXTYPE_PRIVATE5, eLEXTYPE_PRIVATE6, eLEXTYPE_PRIVATE7,
    eLEXTYPE_PRIVATE8, eLEXTYPE_PRIVATE9, eLEXTYPE_RESERVED10, eLEXTYPE_RESERVED4,
    eLEXTYPE_RESERVED6, eLEXTYPE_RESERVED7, eLEXTYPE_RESERVED8, eLEXTYPE_RESERVED9, eLEXTYPE_USER,
    eLEXTYPE_USER_SHORTCUT, eLEXTYPE_VENDORLEXICON, ePRONFLAG_USED, eWORDTYPE_ADDED,
    eWORDTYPE_DELETED, AllWords, ISpContainerLexicon, ISpContainerLexiconVtbl, ISpGrammarBuilder,
    ISpGrammarBuilder2, ISpGrammarBuilder2Vtbl, ISpGrammarBuilderVtbl, ISpLexicon, ISpLexiconVtbl,
    ISpPhoneConverter, ISpPhoneConverterVtbl, ISpPhoneticAlphabetConverter,
    ISpPhoneticAlphabetConverterVtbl, ISpPhoneticAlphabetSelection,
    ISpPhoneticAlphabetSelectionVtbl, ISpPhrase, ISpPhrase2, ISpPhrase2Vtbl, ISpPhraseAlt,
    ISpPhraseAltVtbl, ISpPhraseVtbl, ISpProperties, ISpPropertiesVtbl, ISpRecoContext,
    ISpRecoContext2, ISpRecoContext2Vtbl, ISpRecoContextVtbl, ISpRecoGrammar, ISpRecoGrammar2,
    ISpRecoGrammar2Vtbl, ISpRecoGrammarVtbl, ISpRecoResult, ISpRecoResult2, ISpRecoResult2Vtbl,
    ISpRecoResultVtbl, ISpRecognizer, ISpRecognizer2, ISpRecognizer2Vtbl, ISpRecognizerVtbl,
    ISpSerializeState, ISpSerializeStateVtbl, ISpShortcut, ISpShortcutVtbl, ISpVoice, ISpVoiceVtbl,
    ISpXMLRecoResult, ISpXMLRecoResultVtbl, ISpeechResourceLoader, ISpeechResourceLoaderVtbl,
    OrderedSubset, OrderedSubsetContentRequired, PA_Ipa, PA_Sapi, PA_Ups, SPADS_CurrentRecognizer,
    SPADS_Default, SPADS_HighVolumeDataSource, SPADS_Immediate, SPADS_RecoProfile, SPADS_Reset,
    SPAR_High, SPAR_Low, SPAR_Medium, SPAR_Unknown, SPPS_Function, SPPS_Interjection,
    SPPS_Modifier, SPPS_Noncontent, SPPS_NotOverriden, SPPS_Noun, SPPS_SuppressWord, SPPS_Unknown,
    SPPS_Verb, SPRAF_Active, SPRAF_AutoPause, SPRAF_Dynamic, SPRAF_Export, SPRAF_Import,
    SPRAF_Interpreter, SPRAF_Root, SPRAF_TopLevel, SPRAF_UserDelimited, SPREF_AutoPause,
    SPREF_Emulated, SPREF_ExtendableParse, SPREF_FalseRecognition, SPREF_Hypothesis, SPREF_ReSent,
    SPREF_SMLTimeout, SPSHT_NotOverriden, SPSHT_Unknown, SPVA_Bookmark, SPVA_ParseUnknownTag,
    SPVA_Pronounce, SPVA_Section, SPVA_Silence, SPVA_Speak, SPVA_SpellOut, SPXRO_Alternates_SML,
    Subsequence, SubsequenceContentRequired, PHONETICALPHABET, SPADAPTATIONRELEVANCE,
    SPADAPTATIONSETTINGS, SPAO_NONE, SPAO_RETAIN_AUDIO, SPAUDIOOPTIONS, SPBINARYGRAMMAR,
    SPBOOKMARKOPTIONS, SPBO_AHEAD, SPBO_NONE, SPBO_PAUSE, SPBO_TIME_UNITS, SPCFGRULEATTRIBUTES,
    SPCF_ADD_TO_USER_LEXICON, SPCF_DEFINITE_CORRECTION, SPCF_NONE, SPCOMMITFLAGS, SPCONTEXTSTATE,
    SPCS_DISABLED, SPCS_ENABLED, SPDF_ALL, SPDF_ALTERNATES, SPDF_AUDIO, SPDF_DISPLAYTEXT,
    SPDF_LEXICALFORM, SPDF_PRONUNCIATION, SPDF_PROPERTY, SPDF_REPLACEMENT, SPDF_RULE, SPEAKFLAGS,
    SPF_ASYNC, SPF_DEFAULT, SPF_IS_FILENAME, SPF_IS_NOT_XML, SPF_IS_XML, SPF_NLP_MASK,
    SPF_NLP_SPEAK_PUNC, SPF_PARSE_AUTODETECT, SPF_PARSE_MASK, SPF_PARSE_SAPI, SPF_PARSE_SSML,
    SPF_PERSIST_XML, SPF_PURGEBEFORESPEAK, SPF_UNUSED_FLAGS, SPF_VOICE_MASK, SPGO_ALL,
    SPGO_DEFAULT, SPGO_FILE, SPGO_HTTP, SPGO_OBJECT, SPGO_RES, SPGO_SAPI, SPGO_SRGS,
    SPGO_SRGS_MS_SCRIPT, SPGO_SRGS_SCRIPT, SPGO_SRGS_STG_SCRIPT, SPGO_SRGS_W3C_SCRIPT, SPGO_UPS,
    SPGRAMMAROPTIONS, SPGRAMMARSTATE, SPGS_DISABLED, SPGS_ENABLED, SPGS_EXCLUSIVE, SPLEXICONTYPE,
    SPLOADOPTIONS, SPLO_DYNAMIC, SPLO_STATIC, SPMATCHINGMODE, SPMAX_RATE, SPMAX_VOLUME, SPMIN_RATE,
    SPMIN_VOLUME, SPPARTOFSPEECH, SPPHRASERNG, SPPRONUNCIATIONFLAGS, SPPROPERTYINFO,
    SPPR_ALL_ELEMENTS, SPPS_LMA, SPPS_RESERVED1, SPPS_RESERVED2, SPPS_RESERVED3, SPPS_RESERVED4,
    SPRECOCONTEXTSTATUS, SPRECOEVENTFLAGS, SPRECOGNIZERSTATUS, SPRECORESULTTIMES, SPRECOSTATE,
    SPRP_NORMAL, SPRR_ALL_ELEMENTS, SPRST_ACTIVE, SPRST_ACTIVE_ALWAYS, SPRST_INACTIVE,
    SPRST_INACTIVE_WITH_PURGE, SPRST_NUM_STATES, SPRS_ACTIVE, SPRS_ACTIVE_WITH_AUTO_PAUSE,
    SPRS_DONE, SPRS_INACTIVE, SPRS_IS_SPEAKING, SPRULE, SPRULESTATE, SPRUNSTATE,
    SPSERIALIZEDPHRASE, SPSERIALIZEDRESULT, SPSHORTCUTPAIR, SPSHORTCUTPAIRLIST, SPSHORTCUTTYPE,
    SPSHT_EMAIL, SPSHT_OTHER, SPSTATEHANDLE, SPSTREAMFORMATTYPE, SPTEXTSELECTIONINFO, SPVACTIONS,
    SPVALUETYPE, SPVCONTEXT, SPVLIMITS, SPVOICESTATUS, SPVPITCH, SPVPRIORITY, SPVPRI_ALERT,
    SPVPRI_NORMAL, SPVPRI_OVER, SPVSTATE, SPWAVEFORMATTYPE, SPWF_INPUT, SPWF_SRENGINE, SPWORD,
    SPWORDLIST, SPWORDPRONOUNCEABLE, SPWORDPRONUNCIATION, SPWORDPRONUNCIATIONLIST, SPWORDTYPE,
    SPWP_KNOWN_WORD_PRONOUNCEABLE, SPWP_UNKNOWN_WORD_PRONOUNCEABLE,
    SPWP_UNKNOWN_WORD_UNPRONOUNCEABLE, SPWT_LEXICAL_NO_SPECIAL_CHARS, SPXMLRESULTOPTIONS,
    SPXRO_SML, SP_GETWHOLEPHRASE, SP_MAX_LANGIDS,
};
ENUM! {enum SPCATEGORYTYPE {
    SPCT_COMMAND,
    SPCT_DICTATION,
    SPCT_SLEEP,
    SPCT_SUB_COMMAND,
    SPCT_SUB_DICTATION,
}}
RIDL! {#[uuid(0xda0cd0f9, 0x14a2, 0x4f09, 0x8c, 0x2a, 0x85, 0xcc, 0x48, 0x97, 0x93, 0x45)]
interface ISpRecoCategory(ISpRecoCategoryVtbl): IUnknown(IUnknownVtbl) {
    fn GetType(
        peCategoryType: *mut SPCATEGORYTYPE,
    ) -> HRESULT,
}}
RIDL! {#[uuid(0xdf1b943c, 0x5838, 0x4aa2, 0x87, 0x06, 0xd7, 0xcd, 0x5b, 0x33, 0x34, 0x99)]
interface ISpRecognizer3(ISpRecognizer3Vtbl): IUnknown(IUnknownVtbl) {
    fn GetCategory(
        categoryType: SPCATEGORYTYPE,
        ppCategory: *mut *mut ISpRecoCategory,
    ) -> HRESULT,
    fn SetActiveCategory(
        pCategory: *mut ISpRecoCategory,
    ) -> HRESULT,
    fn GetActiveCategory(
        ppCategory: *mut *mut ISpRecoCategory,
    ) -> HRESULT,
}}
pub use um::sapi53::{
    CLSID_SpAudioFormat, CLSID_SpCompressedLexicon, CLSID_SpCustomStream, CLSID_SpFileStream,
    CLSID_SpInProcRecoContext, CLSID_SpInprocRecognizer, CLSID_SpLexicon, CLSID_SpMMAudioEnum,
    CLSID_SpMMAudioIn, CLSID_SpMMAudioOut, CLSID_SpMemoryStream, CLSID_SpNotifyTranslator,
    CLSID_SpNullPhoneConverter, CLSID_SpObjectToken, CLSID_SpObjectTokenCategory,
    CLSID_SpPhoneConverter, CLSID_SpPhoneticAlphabetConverter, CLSID_SpPhraseInfoBuilder,
    CLSID_SpResourceManager, CLSID_SpSharedRecoContext, CLSID_SpSharedRecognizer, CLSID_SpShortcut,
    CLSID_SpStream, CLSID_SpStreamFormatConverter, CLSID_SpTextSelectionInformation,
    CLSID_SpUnCompressedLexicon, CLSID_SpVoice, CLSID_SpWaveFormatEx, DISPIDSPTSI_ActiveLength,
    DISPIDSPTSI_ActiveOffset, DISPIDSPTSI_SelectionLength, DISPIDSPTSI_SelectionOffset,
    DISPID_SABIBufferSize, DISPID_SABIEventBias, DISPID_SABIMinNotification, DISPID_SABufferInfo,
    DISPID_SABufferNotifySize, DISPID_SADefaultFormat, DISPID_SAEventHandle,
    DISPID_SAFGetWaveFormatEx, DISPID_SAFGuid, DISPID_SAFSetWaveFormatEx, DISPID_SAFType,
    DISPID_SASCurrentDevicePosition, DISPID_SASCurrentSeekPosition, DISPID_SASFreeBufferSpace,
    DISPID_SASNonBlockingIO, DISPID_SASState, DISPID_SASetState, DISPID_SAStatus, DISPID_SAVolume,
    DISPID_SBSFormat, DISPID_SBSRead, DISPID_SBSSeek, DISPID_SBSWrite, DISPID_SCSBaseStream,
    DISPID_SDKCreateKey, DISPID_SDKDeleteKey, DISPID_SDKDeleteValue, DISPID_SDKEnumKeys,
    DISPID_SDKEnumValues, DISPID_SDKGetBinaryValue, DISPID_SDKGetStringValue,
    DISPID_SDKGetlongValue, DISPID_SDKOpenKey, DISPID_SDKSetBinaryValue, DISPID_SDKSetLongValue,
    DISPID_SDKSetStringValue, DISPID_SFSClose, DISPID_SFSOpen, DISPID_SGRAddResource,
    DISPID_SGRAddState, DISPID_SGRAttributes, DISPID_SGRClear, DISPID_SGRId,
    DISPID_SGRInitialState, DISPID_SGRName, DISPID_SGRSAddRuleTransition,
    DISPID_SGRSAddSpecialTransition, DISPID_SGRSAddWordTransition, DISPID_SGRSRule,
    DISPID_SGRSTNextState, DISPID_SGRSTPropertyId, DISPID_SGRSTPropertyName,
    DISPID_SGRSTPropertyValue, DISPID_SGRSTRule, DISPID_SGRSTText, DISPID_SGRSTType,
    DISPID_SGRSTWeight, DISPID_SGRSTransitions, DISPID_SGRSTsCount, DISPID_SGRSTsItem,
    DISPID_SGRSTs_NewEnum, DISPID_SGRsAdd, DISPID_SGRsCommit, DISPID_SGRsCommitAndSave,
    DISPID_SGRsCount, DISPID_SGRsDynamic, DISPID_SGRsFindRule, DISPID_SGRsItem,
    DISPID_SGRs_NewEnum, DISPID_SLAddPronunciation, DISPID_SLAddPronunciationByPhoneIds,
    DISPID_SLGenerationId, DISPID_SLGetGenerationChange, DISPID_SLGetPronunciations,
    DISPID_SLGetWords, DISPID_SLPLangId, DISPID_SLPPartOfSpeech, DISPID_SLPPhoneIds,
    DISPID_SLPSymbolic, DISPID_SLPType, DISPID_SLPsCount, DISPID_SLPsItem, DISPID_SLPs_NewEnum,
    DISPID_SLRemovePronunciation, DISPID_SLRemovePronunciationByPhoneIds, DISPID_SLWLangId,
    DISPID_SLWPronunciations, DISPID_SLWType, DISPID_SLWWord, DISPID_SLWsCount, DISPID_SLWsItem,
    DISPID_SLWs_NewEnum, DISPID_SMSADeviceId, DISPID_SMSALineId, DISPID_SMSAMMHandle,
    DISPID_SMSGetData, DISPID_SMSSetData, DISPID_SOTCDefault, DISPID_SOTCEnumerateTokens,
    DISPID_SOTCGetDataKey, DISPID_SOTCId, DISPID_SOTCSetId, DISPID_SOTCategory,
    DISPID_SOTCreateInstance, DISPID_SOTDataKey, DISPID_SOTDisplayUI, DISPID_SOTGetAttribute,
    DISPID_SOTGetDescription, DISPID_SOTGetStorageFileName, DISPID_SOTId, DISPID_SOTIsUISupported,
    DISPID_SOTMatchesAttributes, DISPID_SOTRemove, DISPID_SOTRemoveStorageFileName,
    DISPID_SOTSetId, DISPID_SOTsCount, DISPID_SOTsItem, DISPID_SOTs_NewEnum, DISPID_SPACommit,
    DISPID_SPANumberOfElementsInResult, DISPID_SPAPhraseInfo, DISPID_SPARecoResult,
    DISPID_SPAStartElementInResult, DISPID_SPAsCount, DISPID_SPAsItem, DISPID_SPAs_NewEnum,
    DISPID_SPCIdToPhone, DISPID_SPCLangId, DISPID_SPCPhoneToId, DISPID_SPEActualConfidence,
    DISPID_SPEAudioSizeBytes, DISPID_SPEAudioSizeTime, DISPID_SPEAudioStreamOffset,
    DISPID_SPEAudioTimeOffset, DISPID_SPEDisplayAttributes, DISPID_SPEDisplayText,
    DISPID_SPEEngineConfidence, DISPID_SPELexicalForm, DISPID_SPEPronunciation,
    DISPID_SPERequiredConfidence, DISPID_SPERetainedSizeBytes, DISPID_SPERetainedStreamOffset,
    DISPID_SPEsCount, DISPID_SPEsItem, DISPID_SPEs_NewEnum, DISPID_SPIAudioSizeBytes,
    DISPID_SPIAudioSizeTime, DISPID_SPIAudioStreamPosition, DISPID_SPIElements, DISPID_SPIEngineId,
    DISPID_SPIEnginePrivateData, DISPID_SPIGetDisplayAttributes, DISPID_SPIGetText,
    DISPID_SPIGrammarId, DISPID_SPILanguageId, DISPID_SPIProperties, DISPID_SPIReplacements,
    DISPID_SPIRetainedSizeBytes, DISPID_SPIRule, DISPID_SPISaveToMemory, DISPID_SPIStartTime,
    DISPID_SPPBRestorePhraseFromMemory, DISPID_SPPChildren, DISPID_SPPConfidence,
    DISPID_SPPEngineConfidence, DISPID_SPPFirstElement, DISPID_SPPId, DISPID_SPPName,
    DISPID_SPPNumberOfElements, DISPID_SPPParent, DISPID_SPPValue, DISPID_SPPsCount,
    DISPID_SPPsItem, DISPID_SPPs_NewEnum, DISPID_SPRDisplayAttributes, DISPID_SPRFirstElement,
    DISPID_SPRNumberOfElements, DISPID_SPRText, DISPID_SPRsCount, DISPID_SPRsItem,
    DISPID_SPRs_NewEnum, DISPID_SPRuleChildren, DISPID_SPRuleConfidence,
    DISPID_SPRuleEngineConfidence, DISPID_SPRuleFirstElement, DISPID_SPRuleId, DISPID_SPRuleName,
    DISPID_SPRuleNumberOfElements, DISPID_SPRuleParent, DISPID_SPRulesCount, DISPID_SPRulesItem,
    DISPID_SPRules_NewEnum, DISPID_SRAllowAudioInputFormatChangesOnNextSet,
    DISPID_SRAllowVoiceFormatMatchingOnNextSet, DISPID_SRAudioInput, DISPID_SRAudioInputStream,
    DISPID_SRCAudioInInterferenceStatus, DISPID_SRCBookmark, DISPID_SRCCmdMaxAlternates,
    DISPID_SRCCreateGrammar, DISPID_SRCCreateResultFromMemory, DISPID_SRCEAdaptation,
    DISPID_SRCEAudioLevel, DISPID_SRCEBookmark, DISPID_SRCEEndStream, DISPID_SRCEEnginePrivate,
    DISPID_SRCEFalseRecognition, DISPID_SRCEHypothesis, DISPID_SRCEInterference,
    DISPID_SRCEPhraseStart, DISPID_SRCEPropertyNumberChange, DISPID_SRCEPropertyStringChange,
    DISPID_SRCERecognition, DISPID_SRCERecognitionForOtherContext,
    DISPID_SRCERecognizerStateChange, DISPID_SRCERequestUI, DISPID_SRCESoundEnd,
    DISPID_SRCESoundStart, DISPID_SRCEStartStream, DISPID_SRCEventInterests, DISPID_SRCPause,
    DISPID_SRCRecognizer, DISPID_SRCRequestedUIType, DISPID_SRCResume, DISPID_SRCRetainedAudio,
    DISPID_SRCRetainedAudioFormat, DISPID_SRCSetAdaptationData, DISPID_SRCState, DISPID_SRCVoice,
    DISPID_SRCVoicePurgeEvent, DISPID_SRCreateRecoContext, DISPID_SRDisplayUI,
    DISPID_SREmulateRecognition, DISPID_SRGCmdLoadFromFile, DISPID_SRGCmdLoadFromMemory,
    DISPID_SRGCmdLoadFromObject, DISPID_SRGCmdLoadFromProprietaryGrammar,
    DISPID_SRGCmdLoadFromResource, DISPID_SRGCmdSetRuleIdState, DISPID_SRGCmdSetRuleState,
    DISPID_SRGCommit, DISPID_SRGDictationLoad, DISPID_SRGDictationSetState,
    DISPID_SRGDictationUnload, DISPID_SRGId, DISPID_SRGIsPronounceable, DISPID_SRGRecoContext,
    DISPID_SRGReset, DISPID_SRGRules, DISPID_SRGSetTextSelection, DISPID_SRGSetWordSequenceData,
    DISPID_SRGState, DISPID_SRGetFormat, DISPID_SRGetPropertyNumber, DISPID_SRGetPropertyString,
    DISPID_SRGetRecognizers, DISPID_SRIsShared, DISPID_SRIsUISupported, DISPID_SRProfile,
    DISPID_SRRAlternates, DISPID_SRRAudio, DISPID_SRRAudioFormat, DISPID_SRRDiscardResultInfo,
    DISPID_SRRGetXMLErrorInfo, DISPID_SRRGetXMLResult, DISPID_SRRPhraseInfo, DISPID_SRRRecoContext,
    DISPID_SRRSaveToMemory, DISPID_SRRSetTextFeedback, DISPID_SRRSpeakAudio, DISPID_SRRTLength,
    DISPID_SRRTOffsetFromStart, DISPID_SRRTStreamTime, DISPID_SRRTTickCount, DISPID_SRRTimes,
    DISPID_SRRecognizer, DISPID_SRSAudioStatus, DISPID_SRSClsidEngine,
    DISPID_SRSCurrentStreamNumber, DISPID_SRSCurrentStreamPosition, DISPID_SRSNumberOfActiveRules,
    DISPID_SRSSupportedLanguages, DISPID_SRSetPropertyNumber, DISPID_SRSetPropertyString,
    DISPID_SRState, DISPID_SRStatus, DISPID_SVAlertBoundary,
    DISPID_SVAllowAudioOuputFormatChangesOnNextSet, DISPID_SVAudioOutput,
    DISPID_SVAudioOutputStream, DISPID_SVDisplayUI, DISPID_SVEAudioLevel, DISPID_SVEBookmark,
    DISPID_SVEEnginePrivate, DISPID_SVEPhoneme, DISPID_SVESentenceBoundary, DISPID_SVEStreamEnd,
    DISPID_SVEStreamStart, DISPID_SVEViseme, DISPID_SVEVoiceChange, DISPID_SVEWord,
    DISPID_SVEventInterests, DISPID_SVGetAudioInputs, DISPID_SVGetAudioOutputs,
    DISPID_SVGetProfiles, DISPID_SVGetVoices, DISPID_SVIsUISupported, DISPID_SVPause,
    DISPID_SVPriority, DISPID_SVRate, DISPID_SVResume, DISPID_SVSCurrentStreamNumber,
    DISPID_SVSInputSentenceLength, DISPID_SVSInputSentencePosition, DISPID_SVSInputWordLength,
    DISPID_SVSInputWordPosition, DISPID_SVSLastBookmark, DISPID_SVSLastBookmarkId,
    DISPID_SVSLastResult, DISPID_SVSLastStreamNumberQueued, DISPID_SVSPhonemeId,
    DISPID_SVSRunningState, DISPID_SVSVisemeId, DISPID_SVSkip, DISPID_SVSpeak,
    DISPID_SVSpeakCompleteEvent, DISPID_SVSpeakStream, DISPID_SVStatus,
    DISPID_SVSyncronousSpeakTimeout, DISPID_SVVoice, DISPID_SVVolume, DISPID_SVWaitUntilDone,
    DISPID_SWFEAvgBytesPerSec, DISPID_SWFEBitsPerSample, DISPID_SWFEBlockAlign,
    DISPID_SWFEChannels, DISPID_SWFEExtraData, DISPID_SWFEFormatTag, DISPID_SWFESamplesPerSec,
    DISPID_SpeechAudio, DISPID_SpeechAudioBufferInfo, DISPID_SpeechAudioFormat,
    DISPID_SpeechAudioStatus, DISPID_SpeechBaseStream, DISPID_SpeechCustomStream,
    DISPID_SpeechDataKey, DISPID_SpeechFileStream, DISPID_SpeechGrammarRule,
    DISPID_SpeechGrammarRuleState, DISPID_SpeechGrammarRuleStateTransition,
    DISPID_SpeechGrammarRuleStateTransitions, DISPID_SpeechGrammarRules, DISPID_SpeechLexicon,
    DISPID_SpeechLexiconProns, DISPID_SpeechLexiconPronunciation, DISPID_SpeechLexiconWord,
    DISPID_SpeechLexiconWords, DISPID_SpeechMMSysAudio, DISPID_SpeechMemoryStream,
    DISPID_SpeechObjectToken, DISPID_SpeechObjectTokenCategory, DISPID_SpeechObjectTokens,
    DISPID_SpeechPhoneConverter, DISPID_SpeechPhraseAlternate, DISPID_SpeechPhraseAlternates,
    DISPID_SpeechPhraseBuilder, DISPID_SpeechPhraseElement, DISPID_SpeechPhraseElements,
    DISPID_SpeechPhraseInfo, DISPID_SpeechPhraseProperties, DISPID_SpeechPhraseProperty,
    DISPID_SpeechPhraseReplacement, DISPID_SpeechPhraseReplacements, DISPID_SpeechPhraseRule,
    DISPID_SpeechPhraseRules, DISPID_SpeechRecoContext, DISPID_SpeechRecoContextEvents,
    DISPID_SpeechRecoResult, DISPID_SpeechRecoResult2, DISPID_SpeechRecoResultTimes,
    DISPID_SpeechRecognizer, DISPID_SpeechRecognizerStatus, DISPID_SpeechVoice,
    DISPID_SpeechVoiceEvent, DISPID_SpeechVoiceStatus, DISPID_SpeechWaveFormatEx,
    DISPID_SpeechXMLRecoResult, ISpDisplayAlternates, ISpDisplayAlternatesVtbl,
    ISpEnginePronunciation, ISpEnginePronunciationVtbl, ISpeechAudio, ISpeechAudioBufferInfo,
    ISpeechAudioBufferInfoVtbl, ISpeechAudioFormat, ISpeechAudioFormatVtbl, ISpeechAudioStatus,
    ISpeechAudioStatusVtbl, ISpeechAudioVtbl, ISpeechBaseStream, ISpeechBaseStreamVtbl,
    ISpeechCustomStream, ISpeechCustomStreamVtbl, ISpeechDataKey, ISpeechDataKeyVtbl,
    ISpeechFileStream, ISpeechFileStreamVtbl, ISpeechGrammarRule, ISpeechGrammarRuleState,
    ISpeechGrammarRuleStateTransition, ISpeechGrammarRuleStateTransitionVtbl,
    ISpeechGrammarRuleStateTransitions, ISpeechGrammarRuleStateTransitionsVtbl,
    ISpeechGrammarRuleStateVtbl, ISpeechGrammarRuleVtbl, ISpeechGrammarRules,
    ISpeechGrammarRulesVtbl, ISpeechLexicon, ISpeechLexiconPronunciation,
    ISpeechLexiconPronunciationVtbl, ISpeechLexiconPronunciations,
    ISpeechLexiconPronunciationsVtbl, ISpeechLexiconVtbl, ISpeechLexiconWord,
    ISpeechLexiconWordVtbl, ISpeechLexiconWords, ISpeechLexiconWordsVtbl, ISpeechMMSysAudio,
    ISpeechMMSysAudioVtbl, ISpeechMemoryStream, ISpeechMemoryStreamVtbl, ISpeechObjectToken,
    ISpeechObjectTokenCategory, ISpeechObjectTokenCategoryVtbl, ISpeechObjectTokenVtbl,
    ISpeechObjectTokens, ISpeechObjectTokensVtbl, ISpeechPhoneConverter, ISpeechPhoneConverterVtbl,
    ISpeechPhraseAlternate, ISpeechPhraseAlternateVtbl, ISpeechPhraseAlternates,
    ISpeechPhraseAlternatesVtbl, ISpeechPhraseElement, ISpeechPhraseElementVtbl,
    ISpeechPhraseElements, ISpeechPhraseElementsVtbl, ISpeechPhraseInfo, ISpeechPhraseInfoBuilder,
    ISpeechPhraseInfoBuilderVtbl, ISpeechPhraseInfoVtbl, ISpeechPhraseProperties,
    ISpeechPhrasePropertiesVtbl, ISpeechPhraseProperty, ISpeechPhrasePropertyVtbl,
    ISpeechPhraseReplacement, ISpeechPhraseReplacementVtbl, ISpeechPhraseReplacements,
    ISpeechPhraseReplacementsVtbl, ISpeechPhraseRule, ISpeechPhraseRuleVtbl, ISpeechPhraseRules,
    ISpeechPhraseRulesVtbl, ISpeechRecoContext, ISpeechRecoContextVtbl, ISpeechRecoGrammar,
    ISpeechRecoGrammarVtbl, ISpeechRecoResult, ISpeechRecoResult2, ISpeechRecoResult2Vtbl,
    ISpeechRecoResultDispatch, ISpeechRecoResultDispatchVtbl, ISpeechRecoResultTimes,
    ISpeechRecoResultTimesVtbl, ISpeechRecoResultVtbl, ISpeechRecognizer, ISpeechRecognizerStatus,
    ISpeechRecognizerStatusVtbl, ISpeechRecognizerVtbl, ISpeechTextSelectionInformation,
    ISpeechTextSelectionInformationVtbl, ISpeechVoice, ISpeechVoiceStatus, ISpeechVoiceStatusVtbl,
    ISpeechVoiceVtbl, ISpeechWaveFormatEx, ISpeechWaveFormatExVtbl, ISpeechXMLRecoResult,
    ISpeechXMLRecoResultVtbl, LIBID_SpeechLib, SAFT11kHz16BitMono, SAFT11kHz16BitStereo,
    SAFT11kHz8BitMono, SAFT11kHz8BitStereo, SAFT12kHz16BitMono, SAFT12kHz16BitStereo,
    SAFT12kHz8BitMono, SAFT12kHz8BitStereo, SAFT16kHz16BitMono, SAFT16kHz16BitStereo,
    SAFT16kHz8BitMono, SAFT16kHz8BitStereo, SAFT22kHz16BitMono, SAFT22kHz16BitStereo,
    SAFT22kHz8BitMono, SAFT22kHz8BitStereo, SAFT24kHz16BitMono, SAFT24kHz16BitStereo,
    SAFT24kHz8BitMono, SAFT24kHz8BitStereo, SAFT32kHz16BitMono, SAFT32kHz16BitStereo,
    SAFT32kHz8BitMono, SAFT32kHz8BitStereo, SAFT44kHz16BitMono, SAFT44kHz16BitStereo,
    SAFT44kHz8BitMono, SAFT44kHz8BitStereo, SAFT48kHz16BitMono, SAFT48kHz16BitStereo,
    SAFT48kHz8BitMono, SAFT48kHz8BitStereo, SAFT8kHz16BitMono, SAFT8kHz16BitStereo,
    SAFT8kHz8BitMono, SAFT8kHz8BitStereo, SAFTADPCM_11kHzMono, SAFTADPCM_11kHzStereo,
    SAFTADPCM_22kHzMono, SAFTADPCM_22kHzStereo, SAFTADPCM_44kHzMono, SAFTADPCM_44kHzStereo,
    SAFTADPCM_8kHzMono, SAFTADPCM_8kHzStereo, SAFTCCITT_ALaw_11kHzMono, SAFTCCITT_ALaw_11kHzStereo,
    SAFTCCITT_ALaw_22kHzMono, SAFTCCITT_ALaw_22kHzStereo, SAFTCCITT_ALaw_44kHzMono,
    SAFTCCITT_ALaw_44kHzStereo, SAFTCCITT_ALaw_8kHzMono, SAFTCCITT_ALaw_8kHzStereo,
    SAFTCCITT_uLaw_11kHzMono, SAFTCCITT_uLaw_11kHzStereo, SAFTCCITT_uLaw_22kHzMono,
    SAFTCCITT_uLaw_22kHzStereo, SAFTCCITT_uLaw_44kHzMono, SAFTCCITT_uLaw_44kHzStereo,
    SAFTCCITT_uLaw_8kHzMono, SAFTCCITT_uLaw_8kHzStereo, SAFTDefault, SAFTExtendedAudioFormat,
    SAFTGSM610_11kHzMono, SAFTGSM610_22kHzMono, SAFTGSM610_44kHzMono, SAFTGSM610_8kHzMono,
    SAFTNoAssignedFormat, SAFTNonStandardFormat, SAFTText, SAFTTrueSpeech_8kHz1BitMono, SASClosed,
    SASPause, SASRun, SASStop, SBONone, SBOPause, SDA_Consume_Leading_Spaces,
    SDA_No_Trailing_Space, SDA_One_Trailing_Space, SDA_Two_Trailing_Spaces, SDKLCurrentConfig,
    SDKLCurrentUser, SDKLDefaultLocation, SDKLLocalMachine, SDTAll, SDTAlternates, SDTAudio,
    SDTDisplayText, SDTLexicalForm, SDTPronunciation, SDTProperty, SDTReplacement, SDTRule,
    SECFDefault, SECFEmulateResult, SECFIgnoreCase, SECFIgnoreKanaType, SECFIgnoreWidth,
    SECFNoSpecialChars, SECHighConfidence, SECLowConfidence, SECNormalConfidence, SFTInput,
    SFTSREngine, SGDSActive, SGDSActiveUserDelimited, SGDSActiveWithAutoPause, SGDSInactive,
    SGDisplay, SGLexical, SGLexicalNoSpecialChars, SGPronounciation, SGRSTTDictation,
    SGRSTTEpsilon, SGRSTTRule, SGRSTTTextBuffer, SGRSTTWildcard, SGRSTTWord, SGSDisabled,
    SGSEnabled, SGSExclusive, SINoSignal, SINoise, SINone, SITooFast, SITooLoud, SITooQuiet,
    SITooSlow, SLODynamic, SLOStatic, SLTApp, SLTUser, SPSFunction, SPSInterjection, SPSModifier,
    SPSNotOverriden, SPSNoun, SPSSuppressWord, SPSUnknown, SPSVerb, SRADefaultToActive, SRADynamic,
    SRAExport, SRAImport, SRAInterpreter, SRAONone, SRAORetainAudio, SRARoot, SRATopLevel,
    SRCS_Disabled, SRCS_Enabled, SREAdaptation, SREAllEvents, SREAudioLevel, SREBookmark,
    SREFalseRecognition, SREHypothesis, SREInterference, SREPhraseStart, SREPrivate,
    SREPropertyNumChange, SREPropertyStringChange, SRERecoOtherContext, SRERecognition,
    SRERequestUI, SRESoundEnd, SRESoundStart, SREStateChange, SREStreamEnd, SREStreamStart,
    SRSActive, SRSActiveAlways, SRSEDone, SRSEIsSpeaking, SRSInactive, SRSInactiveWithPurge,
    SRTAutopause, SRTEmulated, SRTExtendableParse, SRTReSent, SRTSMLTimeout, SRTStandard,
    SSFMCreate, SSFMCreateForWrite, SSFMOpenForRead, SSFMOpenReadWrite,
    SSSPTRelativeToCurrentPosition, SSSPTRelativeToEnd, SSSPTRelativeToStart, SSTTDictation,
    SSTTTextBuffer, SSTTWildcard, STCAll, STCInprocHandler, STCInprocServer, STCLocalServer,
    STCRemoteServer, STSF_AppData, STSF_CommonAppData, STSF_FlagCreate, STSF_LocalAppData,
    SVEAllEvents, SVEAudioLevel, SVEBookmark, SVEEndInputStream, SVEPhoneme, SVEPrivate,
    SVESentenceBoundary, SVEStartInputStream, SVEViseme, SVEVoiceChange, SVEWordBoundary,
    SVF_Emphasis, SVF_None, SVF_Stressed, SVPAlert, SVPNormal, SVPOver, SVSFDefault,
    SVSFIsFilename, SVSFIsNotXML, SVSFIsXML, SVSFNLPMask, SVSFNLPSpeakPunc, SVSFParseAutodetect,
    SVSFParseMask, SVSFParseSapi, SVSFParseSsml, SVSFPersistXML, SVSFPurgeBeforeSpeak,
    SVSFUnusedFlags, SVSFVoiceMask, SVSFlagsAsync, SWPKnownWordPronounceable,
    SWPUnknownWordPronounceable, SWPUnknownWordUnpronounceable, SWTAdded, SWTDeleted,
    SpeechAllElements, SpeechAudioFormatType, SpeechAudioState, SpeechBookmarkOptions,
    SpeechDataKeyLocation, SpeechDiscardType, SpeechDisplayAttributes, SpeechEmulationCompareFlags,
    SpeechEngineConfidence, SpeechFormatType, SpeechGrammarRuleStateTransitionType,
    SpeechGrammarState, SpeechGrammarWordType, SpeechInterference, SpeechLanguageId,
    SpeechLexiconType, SpeechLoadOption, SpeechPartOfSpeech, SpeechRecoContextState,
    SpeechRecoEvents, SpeechRecognitionType, SpeechRecognizerState, SpeechRetainedAudioOptions,
    SpeechRuleAttributes, SpeechRuleState, SpeechRunState, SpeechSpecialTransitionType,
    SpeechStreamFileMode, SpeechStreamSeekPositionType, SpeechTokenContext, SpeechTokenShellFolder,
    SpeechVisemeFeature, SpeechVisemeType, SpeechVoiceEvents, SpeechVoicePriority,
    SpeechVoiceSpeakFlags, SpeechWordPronounceable, SpeechWordType, Speech_Default_Weight,
    Speech_Max_Pron_Length, Speech_Max_Word_Length, Speech_StreamPos_Asap,
    Speech_StreamPos_RealTime, _ISpeechRecoContextEvents, _ISpeechRecoContextEventsVtbl,
    _ISpeechVoiceEvents, _ISpeechVoiceEventsVtbl, DISPIDSPRG, DISPIDSPTSI, SPDISPLAYPHRASE,
    SPDISPLAYTOKEN, SPNORMALIZATIONLIST, SPSLMA, SVP_0, SVP_1, SVP_10, SVP_11, SVP_12, SVP_13,
    SVP_14, SVP_15, SVP_16, SVP_17, SVP_18, SVP_19, SVP_2, SVP_20, SVP_21, SVP_3, SVP_4, SVP_5,
    SVP_6, SVP_7, SVP_8, SVP_9,
};
