// Copyright © 2017 winapi-rs developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// All files in the project carrying such notice may not be copied, modified, or distributed
// except according to those terms.
use um::oaidl::DISPID;
pub const DISPID_SELECTIONCHANGED: DISPID = 200;
pub const DISPID_FILELISTENUMDONE: DISPID = 201;
pub const DISPID_VERBINVOKED: DISPID = 202;
pub const DISPID_DEFAULTVERBINVOKED: DISPID = 203;
pub const DISPID_BEGINDRAG: DISPID = 204;
pub const DISPID_VIEWMODECHANGED: DISPID = 205;
pub const DISPID_NOITEMSTATE_CHANGED: DISPID = 206;
pub const DISPID_CONTENTSCHANGED: DISPID = 207;
pub const DISPID_FOCUSCHANGED: DISPID = 208;
pub const DISPID_CHECKSTATECHANGED: DISPID = 209;
pub const DISPID_ORDERCHANGED: DISPID = 210;
pub const DISPID_VIEWPAINTDONE: DISPID = 211;
pub const DISPID_COLUMNSCHANGED: DISPID = 212;
pub const DISPID_CTRLMOUSEWHEEL: DISPID = 213;
pub const DISPID_SORTDONE: DISPID = 214;
pub const DISPID_ICONSIZECHANGED: DISPID = 215;
pub const DISPID_FOLDERCHANGED: DISPID = 217;
pub const DISPID_FILTERINVOKED: DISPID = 218;
pub const DISPID_WORDWHEELEDITED: DISPID = 219;
pub const DISPID_SELECTEDITEMCHANGED: DISPID = 220;
pub const DISPID_EXPLORERWINDOWREADY: DISPID = 221;
pub const DISPID_UPDATEIMAGE: DISPID = 222;
pub const DISPID_INITIALENUMERATIONDONE: DISPID = 223;
pub const DISPID_ENTERPRISEIDCHANGED: DISPID = 224;
pub const DISPID_ENTERPRESSED: DISPID = 200;
pub const DISPID_SEARCHCOMMAND_START: DISPID = 1;
pub const DISPID_SEARCHCOMMAND_COMPLETE: DISPID = 2;
pub const DISPID_SEARCHCOMMAND_ABORT: DISPID = 3;
pub const DISPID_SEARCHCOMMAND_UPDATE: DISPID = 4;
pub const DISPID_SEARCHCOMMAND_PROGRESSTEXT: DISPID = 5;
pub const DISPID_SEARCHCOMMAND_ERROR: DISPID = 6;
pub const DISPID_SEARCHCOMMAND_RESTORE: DISPID = 7;
pub const DISPID_IADCCTL_DIRTY: DISPID = 0x100;
pub const DISPID_IADCCTL_PUBCAT: DISPID = 0x101;
pub const DISPID_IADCCTL_SORT: DISPID = 0x102;
pub const DISPID_IADCCTL_FORCEX86: DISPID = 0x103;
pub const DISPID_IADCCTL_SHOWPOSTSETUP: DISPID = 0x104;
pub const DISPID_IADCCTL_ONDOMAIN: DISPID = 0x105;
pub const DISPID_IADCCTL_DEFAULTCAT: DISPID = 0x106;
