// Copyright © 2016, Baptiste AUBRY
// Licensed under the MIT License <LICENSE.md>

ENUM_NEG!{enum AVRT_PRIORITY {
    AVRT_PRIORITY_VERYLOW = -2,
    AVRT_PRIORITY_LOW,
    AVRT_PRIORITY_NORMAL,
    AVRT_PRIORITY_HIGH,
    AVRT_PRIORITY_CRITICAL,
}}

pub const THREAD_ORDER_GROUP_INFINITE_TIMEOUT: ::LONGLONG = -1;
