pub const RPC_C_BINDING_INFINITE_TIMEOUT: ::DWORD = 10;
pub const RPC_C_BINDING_MIN_TIMEOUT: ::DWORD = 0;
pub const RPC_C_BINDING_DEFAULT_TIMEOUT: ::DWORD = 5;
pub const RPC_C_BINDING_MAX_TIMEOUT: ::DWORD = 9;

pub const RPC_C_CANCEL_INFINITE_TIMEOUT: ::c_int = -1;

pub const RPC_C_LISTEN_MAX_CALLS_DEFAULT: ::DWORD = 1234;
pub const RPC_C_PROTSEQ_MAX_REQS_DEFAULT: ::DWORD = 10;

pub const RPC_C_BIND_TO_ALL_NICS: ::DWORD = 1;
pub const RPC_C_USE_INTERNET_PORT: ::DWORD = 0x1;
pub const RPC_C_USE_INTRANET_PORT: ::DWORD = 0x2;
pub const RPC_C_DONT_FAIL: ::DWORD = 0x4;

pub const RPC_C_MQ_TEMPORARY: ::DWORD = 0x0000;
pub const RPC_C_MQ_PERMANENT: ::DWORD = 0x0001;
pub const RPC_C_MQ_CLEAR_ON_OPEN: ::DWORD = 0x0002;
pub const RPC_C_MQ_USE_EXISTING_SECURITY: ::DWORD = 0x0004;
pub const RPC_C_MQ_AUTHN_LEVEL_NONE: ::DWORD = 0x0000;
pub const RPC_C_MQ_AUTHN_LEVEL_PKT_INTEGRITY: ::DWORD = 0x0008;
pub const RPC_C_MQ_AUTHN_LEVEL_PKT_PRIVACY: ::DWORD = 0x0010;

pub const RPC_C_OPT_MQ_DELIVERY: ::DWORD = 1;
pub const RPC_C_OPT_MQ_PRIORITY: ::DWORD = 2;
pub const RPC_C_OPT_MQ_JOURNAL: ::DWORD = 3;
pub const RPC_C_OPT_MQ_ACKNOWLEDGE: ::DWORD = 4;
pub const RPC_C_OPT_MQ_AUTHN_SERVICE: ::DWORD = 5;
pub const RPC_C_OPT_MQ_AUTHN_LEVEL: ::DWORD = 6;
pub const RPC_C_OPT_MQ_TIME_TO_REACH_QUEUE: ::DWORD = 7;
pub const RPC_C_OPT_MQ_TIME_TO_BE_RECEIVED: ::DWORD = 8;
pub const RPC_C_OPT_BINDING_NONCAUSAL: ::DWORD = 9;
pub const RPC_C_OPT_SECURITY_CALLBACK: ::DWORD = 10;
pub const RPC_C_OPT_UNIQUE_BINDING: ::DWORD = 11;
pub const RPC_C_OPT_CALL_TIMEOUT: ::DWORD = 12;
pub const RPC_C_OPT_DONT_LINGER: ::DWORD = 13;
pub const RPC_C_OPT_MAX_OPTIONS: ::DWORD = 14;

pub const RPC_C_MQ_EXPRESS: ::DWORD = 0;
pub const RPC_C_MQ_RECOVERABLE: ::DWORD = 1;

pub const RPC_C_MQ_JOURNAL_NONE: ::DWORD = 0;
pub const RPC_C_MQ_JOURNAL_DEADLETTER: ::DWORD = 1;
pub const RPC_C_MQ_JOURNAL_ALWAYS: ::DWORD = 2;

pub const RPC_C_FULL_CERT_CHAIN: ::DWORD = 0x0001;


pub const RPC_C_AUTHN_LEVEL_DEFAULT: ::DWORD = 0;
pub const RPC_C_AUTHN_LEVEL_NONE: ::DWORD = 1;
pub const RPC_C_AUTHN_LEVEL_CONNECT: ::DWORD = 2;
pub const RPC_C_AUTHN_LEVEL_CALL: ::DWORD = 3;
pub const RPC_C_AUTHN_LEVEL_PKT: ::DWORD = 4;
pub const RPC_C_AUTHN_LEVEL_PKT_INTEGRITY: ::DWORD = 5;
pub const RPC_C_AUTHN_LEVEL_PKT_PRIVACY: ::DWORD = 6;

pub const RPC_C_IMP_LEVEL_DEFAULT: ::DWORD = 0;
pub const RPC_C_IMP_LEVEL_ANONYMOUS: ::DWORD = 1;
pub const RPC_C_IMP_LEVEL_IDENTIFY: ::DWORD = 2;
pub const RPC_C_IMP_LEVEL_IMPERSONATE: ::DWORD = 3;
pub const RPC_C_IMP_LEVEL_DELEGATE: ::DWORD = 4;

pub const RPC_C_QOS_IDENTITY_STATIC: ::DWORD = 0;
pub const RPC_C_QOS_IDENTITY_DYNAMIC: ::DWORD = 1;

pub const RPC_C_QOS_CAPABILITIES_DEFAULT: ::DWORD = 0x0;
pub const RPC_C_QOS_CAPABILITIES_MUTUAL_AUTH: ::DWORD = 0x1;
pub const RPC_C_QOS_CAPABILITIES_MAKE_FULLSIC: ::DWORD = 0x2;
pub const RPC_C_QOS_CAPABILITIES_ANY_AUTHORITY: ::DWORD = 0x4;

pub const RPC_C_PROTECT_LEVEL_DEFAULT: ::DWORD = (RPC_C_AUTHN_LEVEL_DEFAULT);
pub const RPC_C_PROTECT_LEVEL_NONE: ::DWORD = (RPC_C_AUTHN_LEVEL_NONE);
pub const RPC_C_PROTECT_LEVEL_CONNECT: ::DWORD = (RPC_C_AUTHN_LEVEL_CONNECT);
pub const RPC_C_PROTECT_LEVEL_CALL: ::DWORD = (RPC_C_AUTHN_LEVEL_CALL);
pub const RPC_C_PROTECT_LEVEL_PKT: ::DWORD = (RPC_C_AUTHN_LEVEL_PKT);
pub const RPC_C_PROTECT_LEVEL_PKT_INTEGRITY: ::DWORD = (RPC_C_AUTHN_LEVEL_PKT_INTEGRITY);
pub const RPC_C_PROTECT_LEVEL_PKT_PRIVACY: ::DWORD = (RPC_C_AUTHN_LEVEL_PKT_PRIVACY);

pub const RPC_C_AUTHN_NONE: ::DWORD = 0;
pub const RPC_C_AUTHN_DCE_PRIVATE: ::DWORD = 1;
pub const RPC_C_AUTHN_DCE_PUBLIC: ::DWORD = 2;
pub const RPC_C_AUTHN_DEC_PUBLIC: ::DWORD = 4;
pub const RPC_C_AUTHN_GSS_NEGOTIATE: ::DWORD = 9;
pub const RPC_C_AUTHN_WINNT: ::DWORD = 10;
pub const RPC_C_AUTHN_GSS_SCHANNEL: ::DWORD = 14;
pub const RPC_C_AUTHN_GSS_KERBEROS: ::DWORD = 16;
pub const RPC_C_AUTHN_DPA: ::DWORD = 17;
pub const RPC_C_AUTHN_MSN: ::DWORD = 18;
pub const RPC_C_AUTHN_DIGEST: ::DWORD = 21;
pub const RPC_C_AUTHN_MQ: ::DWORD = 100;
pub const RPC_C_AUTHN_DEFAULT: ::DWORD = 0xFFFFFFFF;

pub const RPC_C_NO_CREDENTIALS: ::DWORD = 0xFFFFFFFF;

pub const RPC_C_SECURITY_QOS_VERSION: ::DWORD = 1;
pub const RPC_C_SECURITY_QOS_VERSION_1: ::DWORD = 1;
