// Copyright © 2015-2017 winapi-rs developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// All files in the project carrying such notice may not be copied, modified, or distributed
// except according to those terms.
//! This module contains definitions for use with WinMM.

pub type MCIDEVICEID = ::UINT;
pub type MCIERROR = ::DWORD;
pub type YIELDPROC = ::DWORD;

pub const MCIERR_NO_ERROR: DWORD = 0;
pub const MCIERR_UNRECOGNIZED_KEYWORD: DWORD = 259;
pub const MCIERR_UNRECOGNIZED_COMMAND: DWORD = 261;
pub const MCIERR_HARDWARE: DWORD = 262;
pub const MCIERR_INVALID_DEVICE_NAME: DWORD = 263;
pub const MCIERR_OUT_OF_MEMORY: DWORD = 264;
pub const MCIERR_DEVICE_OPEN: DWORD = 265;
pub const MCIERR_CANNOT_LOAD_DRIVER: DWORD = 266;
pub const MCIERR_MISSING_COMMAND_STRING: DWORD = 267;
pub const MCIERR_PARAM_OVERFLOW: DWORD = 268;
pub const MCIERR_MISSING_STRING_ARGUMENT: DWORD = 269;
pub const MCIERR_BAD_INTEGER: DWORD = 270;
pub const MCIERR_PARSER_INTERNAL: DWORD = 271;
pub const MCIERR_DRIVER_INTERNAL: DWORD = 272;
pub const MCIERR_MISSING_PARAMETER: DWORD = 273;
pub const MCIERR_UNSUPPORTED_FUNCTION: DWORD = 274;
pub const MCIERR_FILE_NOT_FOUND: DWORD = 275;
pub const MCIERR_DEVICE_NOT_READY: DWORD = 276;
pub const MCIERR_INTERNAL: DWORD = 277;
pub const MCIERR_DRIVER: DWORD = 278;
pub const MCIERR_CANNOT_USE_ALL: DWORD = 279;
pub const MCIERR_MULTIPLE: DWORD = 280;
pub const MCIERR_EXTENSION_NOT_FOUND: DWORD = 281;
pub const MCIERR_OUTOFRANGE: DWORD = 282;
pub const MCIERR_FLAGS_NOT_COMPATIBLE: DWORD = 284;
pub const MCIERR_FILE_NOT_SAVED: DWORD = 286;
pub const MCIERR_DEVICE_TYPE_REQUIRED: DWORD = 287;
pub const MCIERR_DEVICE_LOCKED: DWORD = 288;
pub const MCIERR_DUPLICATE_ALIAS: DWORD = 289;
pub const MCIERR_BAD_CONSTANT: DWORD = 290;
pub const MCIERR_MUST_USE_SHAREABLE: DWORD = 291;
pub const MCIERR_MISSING_DEVICE_NAME: DWORD = 292;
pub const MCIERR_BAD_TIME_FORMAT: DWORD = 293;
pub const MCIERR_NO_CLOSING_QUOTE: DWORD = 294;
pub const MCIERR_DUPLICATE_FLAGS: DWORD = 295;
pub const MCIERR_INVALID_FILE: DWORD = 296;
pub const MCIERR_NULL_PARAMETER_BLOCK: DWORD = 297;
pub const MCIERR_UNNAMED_RESOURCE: DWORD = 298;
pub const MCIERR_NEW_REQUIRES_ALIAS: DWORD = 299;
pub const MCIERR_NOTIFY_ON_AUTO_OPEN: DWORD = 300;
pub const MCIERR_NO_ELEMENT_ALLOWED: DWORD = 301;
pub const MCIERR_NONAPPLICABLE_FUNCTION: DWORD = 302;
pub const MCIERR_ILLEGAL_FOR_AUTO_OPEN: DWORD = 303;
pub const MCIERR_FILENAME_REQUIRED: DWORD = 304;
pub const MCIERR_EXTRA_CHARACTERS: DWORD = 305;
pub const MCIERR_DEVICE_NOT_INSTALLED: DWORD = 306;
pub const MCIERR_GET_CD: DWORD = 307;
pub const MCIERR_SET_CD: DWORD = 308;
pub const MCIERR_SET_DRIVE: DWORD = 309;
pub const MCIERR_DEVICE_LENGTH: DWORD = 310;
pub const MCIERR_DEVICE_ORD_LENGTH: DWORD = 311;
pub const MCIERR_NO_INTEGER: DWORD = 312;
pub const MCIERR_WAVE_OUTPUTSINUSE: DWORD = 320;
pub const MCIERR_WAVE_SETOUTPUTINUSE: DWORD = 321;
pub const MCIERR_WAVE_INPUTSINUSE: DWORD = 322;
pub const MCIERR_WAVE_SETINPUTINUSE: DWORD = 323;
pub const MCIERR_WAVE_OUTPUTUNSPECIFIED: DWORD = 324;
pub const MCIERR_WAVE_INPUTUNSPECIFIED: DWORD = 325;
pub const MCIERR_WAVE_OUTPUTSUNSUITABLE: DWORD = 326;
pub const MCIERR_WAVE_SETOUTPUTUNSUITABLE: DWORD = 327;
pub const MCIERR_WAVE_INPUTSUNSUITABLE: DWORD = 328;
pub const MCIERR_WAVE_SETINPUTUNSUITABLE: DWORD = 329;
pub const MCIERR_SEQ_DIV_INCOMPATIBLE: DWORD = 336;
pub const MCIERR_SEQ_PORT_INUSE: DWORD = 337;
pub const MCIERR_SEQ_PORT_NONEXISTENT: DWORD = 338;
pub const MCIERR_SEQ_PORT_MAPNODEVICE: DWORD = 339;
pub const MCIERR_SEQ_PORT_MISCERROR: DWORD = 340;
pub const MCIERR_SEQ_TIMER: DWORD = 341;
pub const MCIERR_SEQ_PORTUNSPECIFIED: DWORD = 342;
pub const MCIERR_SEQ_NOMIDIPRESENT: DWORD = 343;
pub const MCIERR_NO_WINDOW: DWORD = 346;
pub const MCIERR_CREATEWINDOW: DWORD = 347;
pub const MCIERR_FILE_READ: DWORD = 348;
pub const MCIERR_FILE_WRITE: DWORD = 349;
pub const MCIERR_NO_IDENTITY: DWORD = 350;
pub const MCIERR_CUSTOM_DRIVER_BASE: DWORD = 512;
